/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_SHARED_FITRESPONSE_v2_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_SHARED_FITRESPONSE_v2_H

#include <fit/stl/string.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace broker {
namespace shared {
struct FitResponseV2 : public FitBase {
    int32_t code {};
    Fit::string message {};
    Fit::bytes data {};
};
}
}
}
}
}
#endif
