management:
  endpoints:
    web:
      exposure:
        include: gateway,health
  endpoint:
    gateway:
      enabled: true

server:
  port: 8003

spring:
  application:
    name: model-gateway-service
  cloud:
    gateway:
      routes:
      # 可在下方添加自定义静态路由信息

      httpclient:
        websocket:
          max-frame-payload-length: 104857600
