/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_SYSTEM_WORKER_GETDISABLEDFITABLES_H
#define COM_HUAWEI_FIT_HAKUNA_SYSTEM_WORKER_GETDISABLEDFITABLES_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_system_worker_genericable_info/1.0.0/cplusplus/genericableInfo.hpp>
#include <fit/stl/vector.hpp>

namespace fit {
namespace hakuna {
namespace system {
namespace worker {
struct __getDisabledFitables {
    using OutType = ::Fit::Framework::ArgumentsOut<Fit::vector<::fit::hakuna::system::worker::GenericableInfo> **>;
};

/**
 * 获取被禁用的fitable列表
 * @return 被禁用的fitable列表
 */
class getDisabledFitables : public ::Fit::Framework::ProxyClient<FitCode(__getDisabledFitables::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "57adc47c358b45bca2ab2e6c26e88e61";
    getDisabledFitables() : ::Fit::Framework::ProxyClient<FitCode(__getDisabledFitables::OutType)>(GENERIC_ID) {}
    ~getDisabledFitables() = default;
};
}
}
}
}

#endif
