/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_LISTENER_MARKFITABLEADDRESSSTATUS_G_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_LISTENER_MARKFITABLEADDRESSSTATUS_G_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Worker/1.0.0/cplusplus/Worker.hpp>
#include <component/com_huawei_fit_hakuna_kernel_shared_Fitable/1.0.0/cplusplus/Fitable.hpp>
namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace listener {
struct __markFitableAddressStatus {
    using InType = ::Fit::Framework::ArgumentsIn<const ::fit::hakuna::kernel::shared::Fitable *,
        const ::fit::hakuna::kernel::registry::shared::Worker *, const bool *>;
};

/**
 *
 * @param fitable
 * @param worker
 * @param valid
 */
class markFitableAddressStatus : public ::Fit::Framework::ProxyClient<FitCode(__markFitableAddressStatus::InType)> {
public:
    static constexpr const char *GENERIC_ID = "134459fe5ade47fe9989866598bd77d2";
    markFitableAddressStatus() : ::Fit::Framework::ProxyClient<FitCode(__markFitableAddressStatus::InType)>(GENERIC_ID)
    {}
    explicit markFitableAddressStatus(ContextObj ctx)
        : ::Fit::Framework::ProxyClient<FitCode(__markFitableAddressStatus::InType)>(GENERIC_ID, ctx)
    {}
    ~markFitableAddressStatus() = default;
};
}
}
}
}
}

#endif
