/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_MATATA_CONF_CLIENT_SET_H
#define COM_HUAWEI_MATATA_CONF_CLIENT_SET_H

#include <fit/external/framework/proxy_client.hpp>

#include <fit/stl/string.hpp>

namespace matata {
namespace conf {
namespace client {
struct __set {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::string *, const Fit::string *>;
};

/**
 * 设置配置的值。
 *
 * @param key 表示配置的键，配置的键将以“.”分割成路径。
 * @param value 表示配置的值。
 */
class set : public ::Fit::Framework::ProxyClient<FitCode(__set::InType)> {
public:
    static constexpr const char *GENERIC_ID = "aec0bab8606344d6913acc8957fbe81d";
    set() : ::Fit::Framework::ProxyClient<FitCode(__set::InType)>(GENERIC_ID) {}
    ~set() = default;
};
}
}
}

#endif
