/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HEARTBEAT_UNSUBSCRIBEHEARTBEAT_H
#define COM_HUAWEI_FIT_HEARTBEAT_UNSUBSCRIBEHEARTBEAT_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_registry_registry_common/1.0.0/cplusplus/registryCommon.hpp>
#include <component/com_huawei_fit_heartbeat_heartbeat_common/1.0.0/cplusplus/heartbeatCommon.hpp>
#include <fit/stl/vector.hpp>

namespace fit {
namespace heartbeat {
struct __unsubscribeHeartbeat {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::vector<::fit::heartbeat::SubscribeBeatInfo> *,
        const ::fit::registry::Address *>;
    using OutType = ::Fit::Framework::ArgumentsOut<bool **>;
};

class unsubscribeHeartbeat
    : public ::Fit::Framework::ProxyClient<FitCode(__unsubscribeHeartbeat::InType, __unsubscribeHeartbeat::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "b66f4694c3724f849ae94c6c94692327";
    unsubscribeHeartbeat()
        : ::Fit::Framework::ProxyClient<FitCode(__unsubscribeHeartbeat::InType, __unsubscribeHeartbeat::OutType)>(
        GENERIC_ID)
    {}
    ~unsubscribeHeartbeat() = default;
};
}
}

#endif