# build.yml自定义路径参考：https://wiki.huawei.com/domains/933/wiki/8/WIKI2021092200325?title=_28
---
version: 2.0

# 构建环境
# 了解如何进行环境配置：http://cloudbuild-doc.inhuawei.com/chapter3/section24.html
# 获取构建环境列表：https://wiki.huawei.com/domains/933/wiki/8/WIKI2021092200325?title=_24
env:
  resource:
    type: "docker"
    image: kweecr04.his.huawei.com:80/ecr-build-arm-gzkunpeng/yf_202306012:2.0
    mode: toolbox
    pool: eks-build-x86-gz-kunpeng-ondocker-16u-02

# 构建参数
# 解如何配置构建参数：http://cloudbuild-doc.inhuawei.com/chapter3/section23.html
params:
  - name: module_name
    value: fit-start



# 构建步骤
# 了解如何配置构建步骤：http://cloudbuild-doc.inhuawei.com/chapter3/section25.html
steps:
  PRE_BUILD: # 了解如何配置构建准备阶段：http://cloudbuild-doc.inhuawei.com/chapter3/section26.html
    - checkout
  BUILD: # 了解如何配置构建执行步骤：http://cloudbuild-doc.inhuawei.com/chapter3/plugins-in-build-stage.html
    - build_execute:
        # ${build_type}、${version}来自全局变量：https://wiki.huawei.com/domains/933/wiki/8/WIKI2022033101320?title=99a4cc30
        # ${CLOUD_BUILD_REPO_REVISION}、${EDEVOPS_TIMESTAMP}来至：http://cloudbuild-doc.inhuawei.com/chapter3/section46.html
        command: sh ./c_pipeline_build.sh ${module_name}
        check: false
