# build.yml自定义路径参考：https://wiki.huawei.com/domains/933/wiki/8/WIKI2021092200325?title=_28
---
version: 2.0

# 构建环境
# 了解如何进行环境配置：http://cloudbuild-doc.inhuawei.com/chapter3/section24.html
# 获取构建环境列表：https://wiki.huawei.com/domains/933/wiki/8/WIKI2021092200325?title=_24
env:
  resource:
    type: "docker"
    image: 'szvecr02.his.huawei.com:80/ecr-build/fit_java1.8u292_build:1.0.0'
    class: 4U8G
    pool: ''

# 构建参数
# 解如何配置构建参数：http://cloudbuild-doc.inhuawei.com/chapter3/section23.html
params:
  - name: module_name
    value: fit-start

# 构建步骤
# 了解如何配置构建步骤：http://cloudbuild-doc.inhuawei.com/chapter3/section25.html
steps:
  PRE_BUILD: # 了解如何配置构建准备阶段：http://cloudbuild-doc.inhuawei.com/chapter3/section26.html
    - checkout
  BUILD: # 了解如何配置构建执行步骤：http://cloudbuild-doc.inhuawei.com/chapter3/plugins-in-build-stage.html
    - build_execute:
        command: sh ./c_test_coverage_build_g.sh ${gitUser} ${gitPwd} ${TARGET_BRANCH} ${TARGET_REPO}
        check: false
  POST_BUILD:
    - sh:
        command: |-
          echo "will exec test and upload to codeCov ENV_SERVICE_NAME is ${ENV_SERVICE_NAME}"
          cd ${WORKSPACE}/jober/
          ls
          curl -k "https://codecov.rnd.huawei.com/rest/codecov/freeExecShell/getShContent/1696133421196726273" -o codecov.sh
          bash -x ./codecov.sh
