# Generated by simpo 0.6.1-dev FlatBuffers schema compiler for C by DOPRA cc

# -*- coding: utf-8 -*-
# Generated by the simpo tool.  DO NOT EDIT!
from cros import CrosService
from fit_py_infra_cros_server.fitRpcServiceUsrApi import RequestResponse
from fitframework.core.network.proto.fit_rpc_service_pb2 import msgRequest
from libcrospython import CROS_PythonApiReg


def RequestResponse_wrapper(input_msg):
    local_input_msg = msgRequest()
    local_input_msg.ParseFromString(input_msg)
    result = RequestResponse(local_input_msg)
    packed_msg = result.SerializeToString()
    return packed_msg


class fitRpcService(CrosService):
    def __init__(self, listen_addr):
        super().__init__('fitRpcService', listen_addr)

        CROS_PythonApiReg('fitRpcService', 'RequestResponse', RequestResponse_wrapper)
