# Generated by simpo 0.6.1-dev FlatBuffers schema compiler for C by DOPRA cc

# -*- coding: utf-8 -*-
# Generated by the simpo tool.  DO NOT EDIT!
from cros import CrosServiceStub, CrosMsgHead, RPC_REQ_MSG_TYPE_SYNC


class fitRpcServiceStub(CrosServiceStub):
    def __init__(self, svr_addr):
        super().__init__(svr_addr, 'fitRpcService')

    def RequestResponse(self, input_msg, output_msg, attr):
        msg_head = CrosMsgHead()
        msg_head.pcServiceName = b'fitRpcService'
        msg_head.pcOperation = b'RequestResponse'
        msg_head.unSessionHdr.stReqHead.ucReqType = RPC_REQ_MSG_TYPE_SYNC
        CrosServiceStub.prepare_req_msg(msg_head, input_msg)
        return self.rpc_sync_call(msg_head, output_msg, attr)

