/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_SYSTEM_WORKER_SETFITABLESTATUS_H
#define COM_HUAWEI_FIT_HAKUNA_SYSTEM_WORKER_SETFITABLESTATUS_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_system_worker_genericable_info/1.0.0/cplusplus/genericableInfo.hpp>
namespace fit {
namespace hakuna {
namespace system {
namespace worker {
struct __setFitableStatus {
    using InType = ::Fit::Framework::ArgumentsIn<const ::fit::hakuna::system::worker::GenericableInfo *, const bool *>;
};

/**
 * 设置服务的启动与否（激活/失活）
 *
 * @param genericableInfo
 * @param enabled：true为激活，false为失活
 */
class setFitableStatus : public ::Fit::Framework::ProxyClient<FitCode(__setFitableStatus::InType)> {
public:
    static constexpr const char *GENERIC_ID = "8c53ac89a572405cbe6cec9f6f66a8fc";
    setFitableStatus() : ::Fit::Framework::ProxyClient<FitCode(__setFitableStatus::InType)>(GENERIC_ID) {}
    ~setFitableStatus() = default;
};
}
}
}
}

#endif
