/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_MATATA_NOTIFICATION_CLIENT_SUBSCRIBE_H
#define COM_HUAWEI_MATATA_NOTIFICATION_CLIENT_SUBSCRIBE_H

#include <fit/external/framework/proxy_client.hpp>

#include <fit/stl/string.hpp>

namespace matata {
namespace notification {
namespace client {
struct __subscribe {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::string *, const Fit::string *, const Fit::string *>;
};

/**
 * 订阅通知。
 *
 * @param consumer 表示消费方的名称。
 * @param topic 表示通知的主题。
 * @param fitableId 表示消费方的fitable的唯一标识。
 */
class subscribe : public ::Fit::Framework::ProxyClient<FitCode(__subscribe::InType)> {
public:
    static constexpr const char *GENERIC_ID = "7a896417dc764a7fbb0381bcf128e9ec";
    subscribe() : ::Fit::Framework::ProxyClient<FitCode(__subscribe::InType)>(GENERIC_ID) {}
    ~subscribe() = default;
};
}
}
}

#endif
