/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_MATATA_CONF_SUBSCRIPTION_CLIENT_APPEND_H
#define COM_HUAWEI_MATATA_CONF_SUBSCRIPTION_CLIENT_APPEND_H

#include <fit/external/framework/proxy_client.hpp>

#include <fit/stl/string.hpp>
#include <fit/stl/vector.hpp>

namespace matata {
namespace conf {
namespace subscription {
namespace client {
struct __append {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::string *, const Fit::vector<Fit::string> *>;
};

/**
 * 将配置路径加入到订阅组中。
 *
 * @param subscription 表示订阅组的名称的字符串。
 * @param paths 表示待加入到订阅组的配置路径的集合。
 */
class append : public ::Fit::Framework::ProxyClient<FitCode(__append::InType)> {
public:
    static constexpr const char *GENERIC_ID = "519a0010b6e943ec9848f9b77b27fd1d";
    append() : ::Fit::Framework::ProxyClient<FitCode(__append::InType)>(GENERIC_ID) {}
    ~append() = default;
};
}
}
}
}

#endif
