apiVersion: v1
kind: Service
metadata:
  name: {{name}}
  labels:
    app: {{name}}_pipeline
    pipeline: {{pipeline_name}}
    task: {{task}}
  namespace: model-io
spec:
  type: NodePort
  ports:
    - port: {{node_port}} # Will be exposed by the service
      targetPort: 9991 # Port of container
  selector:
    app: {{name}}_pipeline
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{name}}-pipeline             # The value of this parameter must be consistent with the name of ConfigMap.
  labels:
    app: {{name}}-pipeline
  namespace: model-io
spec:
  replicas: 1                        # The value of replicas is 1 in a single-node scenario and N in an N-node scenario. The number of NPUs in the requests field is 8 in an N-node scenario.
  selector:
    matchLabels:
      app: {{name}}_pipeline
  template:
    metadata:
      labels:
        app: {{name}}_pipeline
    spec:
      containers:
        - image: {{image_name}}
          imagePullPolicy: Never
          securityContext:
            privileged: true
          name: pipeline-{{name}}
          command: ["/bin/bash"]
          args: ["/root/model-io-pipeline/start_pipeline.sh"]
          env:
          - name: ModelName
            value: {{model_name}}
          - name: Port
            value: "9991"
          - name: Task
            value: {{task}}
          - name: TRANSFORMERS_OFFLINE
            value: "YES"
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: 9991
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: 9991
            initialDelaySeconds: 60
            periodSeconds: 60
          volumeMounts:
          - name: ascend-driver
            mountPath: /usr/local/Ascend/driver
          - name: localtime
            mountPath: /etc/localtime
          - name: npu-smi
            mountPath: /usr/local/bin/npu-smi
          - name: huggingface-path
            mountPath: /root/.cache/huggingface/
          ports:
            - containerPort: 9991
              protocol: TCP
      volumes:
      - name: ascend-driver
        hostPath:
          path: /usr/local/Ascend/driver                              # Configure the NPU driver and mount it to Docker.
      - name: localtime
        hostPath:
          path: /etc/localtime                                        # Configure the Docker time.
      - name: remote
        hostPath:
          path: /mnt/remote
      - name: npu-smi
        hostPath:
          path: /usr/local/bin/npu-smi
      - name: huggingface-path
        hostPath:
          path: /root/.cache/huggingface/
