apiVersion: v1
kind: Service
metadata:
  name: infer-svc-{{name}}
  labels:
    app: {{name}}_inference
  namespace: model-io
spec:
  type: NodePort
  ports:
    - port: {{node_port}} # Will be exposed by the service
      targetPort: 9981 # Port of container
  selector:
    app: {{name}}_inference
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{name}}-inference             # The value of this parameter must be consistent with the name of ConfigMap.
  labels:
    app: {{name}}-inference
  namespace: model-io
spec:
  replicas: {{replicas}}                        # The value of replicas is 1 in a single-node scenario and N in an N-node scenario. The number of NPUs in the requests field is 8 in an N-node scenario.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{name}}_inference
  template:
    metadata:
      labels:
        app: {{name}}_inference
    spec:
      containers:
        - image: {{image_name}}
          imagePullPolicy: Never
          securityContext:
            privileged: {% if enable_npu_schedule %}false{% else %}true{% endif %}
          name: infer-{{name}}
          command: ["/bin/bash"]
          args: ["/root/mindie/start_mindie.sh"]
{%- if enable_npu_schedule %}
          resources:
            requests:
              huawei.com/Ascend910: {{npus}}
            limits:
              huawei.com/Ascend910: {{npus}}
{%- endif %}
          env:
          - name: ModelName
            value: {{name}}
          - name: ModelWeightPath
            value: {{model_weight_path}}
          - name: WorldSize
            value: {% if enable_npu_schedule %}"{{npus}}"{% else %}"1"{% endif %}
          - name: Port
            value: "9981"
          - name: MaxTokenSize
            value: {{max_token_size}}
          readinessProbe:
            httpGet:
              path: /v2/health/ready
              port: 9981
            initialDelaySeconds: 60
            periodSeconds: {% if name == 'qwen-72b' %}60{% else %}10{% endif %}
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: 9981
            initialDelaySeconds: 60
            periodSeconds: {% if name == 'qwen-72b' %}60{% else %}10{% endif %}
            failureThreshold: 6
          volumeMounts:
          - name: ascend-driver
            mountPath: /usr/local/Ascend/driver
          - name: localtime
            mountPath: /etc/localtime
          - name: npu-smi
            mountPath: /usr/local/bin/npu-smi
          - name: model-weight-path
            mountPath: {{model_weight_path}}
          ports:
            - containerPort: 9981
              protocol: TCP
      volumes:
      - name: ascend-driver
        hostPath:
          path: /usr/local/Ascend/driver                              # Configure the NPU driver and mount it to Docker.
      - name: localtime
        hostPath:
          path: /etc/localtime                                        # Configure the Docker time.
      - name: remote
        hostPath:
          path: /mnt/remote
      - name: npu-smi
        hostPath:
          path: /usr/local/bin/npu-smi
      - name: model-weight-path
        hostPath:
          path: {{model_weight_path}}
