/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_MATATA_NOTIFICATION_CLIENT_CONSUME_H
#define COM_HUAWEI_MATATA_NOTIFICATION_CLIENT_CONSUME_H

#include <fit/external/framework/proxy_client.hpp>

#include <fit/stl/string.hpp>

namespace matata {
namespace notification {
namespace client {
struct __consume {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::string *, const Fit::bytes *>;
};

/**
 * 消费通知。
 *
 * @param topic 通知的主题。
 * @param data 通知的内容。
 */
class consume : public ::Fit::Framework::ProxyClient<FitCode(__consume::InType)> {
public:
    static constexpr const char *GENERIC_ID = "bd82ccd28c6047afa85818e835a4c3d7";
    consume() : ::Fit::Framework::ProxyClient<FitCode(__consume::InType)>(GENERIC_ID) {}
    ~consume() = default;
};
}
}
}

#endif