/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_SHARED_FITABLE_C_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_SHARED_FITABLE_C_H

#include <fit/stl/string.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace shared {
struct Fitable : public FitBase {
    Fit::string genericableId {};
    Fit::string genericableVersion {};
    Fit::string fitableId {};
    Fit::string fitableVersion {};
};
}
}
}
}

#endif