export const httpUrlMap = {
  development: {
    JANE_URL: '/aippApi',
    ELSA_URL: '/else',
    AI_URL: '/aiApi',
    AIPP_URL: '/aippApi',
    KNOWLEDGE_URL: '/api/jober/knowledge',
    ICON_URL: 'https://jane-beta.huawei.com/api',
    PUBLISH_URL: 'https://jane-beta.huawei.com/appbuilder/#',
    WS_URL: 'ws://10.169.58.7:8080/v1/api/aipp/streamLog',
    WS_AUDIO_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/asr',
    MODEL_URL: '/modelApi',
    APP_URL: '/app',
    MODEL_LIST_URL: '/api/model_io_manager/v1',
    PLUGIN_URL: '/api/jober',
    MODEL_MANAGE_URL: '/modelbase',
    FINETUNE_URL: '/modeltrain',
    CONDITION_URL: 'https://tzaip.rnd.huawei.com/tzaip/api/hisp/api/v1',
    TT_URL: '/ttApi',
  },
  production: {
    JANE_URL: '/appengine/api',
    AI_URL: '/appengine/tzaip/api/hisp',
    AIPP_URL: '/appengine/api/jober/v1/api',
    MODEL_URL: '/appengine/api',
    MODEL_LIST_URL: `/appengine/api/model_io_manager/v1`,
    PLUGIN_URL: '/appengine/api/jober',
    COLLECT_URL: '/appengine/api/jober/aipp',
    APP_URL: '/appengine/api/jober',
    KNOWLEDGE_URL: '/appengine/api/jober/knowledge',
    TT_URL: 'https://tianzhou.huawei.com',
  },
  gamma: {
    JANE_URL: 'https://jane-gamma.huawei.com/api',
    ICON_URL: 'https://jane-gamma.huawei.com/api',
    ELSA_URL: 'https://fit-elsa-gamma.lab.huawei.com',
    AI_URL: 'https://tzaip-beta.paas.huawei.com/tzaip/api/hisp',
    AIPP_URL: 'https://jane-gamma.huawei.com/api/jober/v1/api',
    PUBLISH_URL: 'https://jane-gamma.huawei.com/appbuilder/#',
    WS_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/chat',
    WS_AUDIO_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/asr',
    MODEL_URL: 'https://tzaip-beta.paas.huawei.com/api',
    MODEL_LIST_URL: '/v1',
    PLUGIN_URL: '/api/jober',
    CONDITION_URL: 'https://tzaip.rnd.huawei.com/tzaip/api/hisp/api/v1',
    TT_URL: 'https://tianzhou-gamma.huawei.com',
  },
  beta: {
    JANE_URL: 'https://jane-beta.huawei.com/api',
    ICON_URL: 'https://jane-beta.huawei.com/api',
    ELSA_URL: 'https://fit-elsa-alpha.lab.huawei.com',
    AI_URL: 'https://tzaip-beta.paas.huawei.com/tzaip/api/hisp',
    AIPP_URL: 'https://jane-beta.huawei.com/api/jober/v1/api',
    PUBLISH_URL: 'https://jane-beta.huawei.com/appbuilder/#',
    WS_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/chat',
    WS_AUDIO_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/asr',
    MODEL_URL: 'https://tzaip-beta.paas.huawei.com/api',
    MODEL_LIST_URL: '/v1',
    PLUGIN_URL: '/api/jober',
    CONDITION_URL: 'https://tzaip.rnd.huawei.com/tzaip/api/hisp/api/v1',
    TT_URL: 'https://tianzhou-beta.huawei.com',
  },
  alpha: {
    JANE_URL: 'https://jane-alpha.huawei.com/api',
    ICON_URL: 'https://jane-alpha.huawei.com/api',
    ELSA_URL: 'https://fit-elsa-alpha.lab.huawei.com',
    AI_URL: 'https://tzaip-beta.paas.huawei.com/tzaip/api/hisp',
    PUBLISH_URL: 'https://jane-alpha.huawei.com/appbuilder/#',
    AIPP_URL: 'https://jane-alpha.huawei.com/api/jober/v1/api',
    WS_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/chat',
    WS_AUDIO_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/asr',
    MODEL_URL: 'https://tzaip-beta.paas.huawei.com/api',
    MODEL_LIST_URL: '/v1',
    PLUGIN_URL: '/api/jober',
    CONDITION_URL: 'https://tzaip.rnd.huawei.com/tzaip/api/hisp/api/v1',
    TT_URL: 'https://https://tianzhou-beta.huawei.com',
  },
};
