export const httpUrlMap = {
  development: {
    JANE_URL: '/aippApi',
    AI_URL: '/aiApi',
    AIPP_URL: '/aippApi',
    APP_URL: '/app',
    PLUGIN_URL: '/api/jober',
    EVALUATE_URL: '/evaluate',
    LOGIN_URL: '/loginApi',
  },
  production: {
    JANE_URL: '/appengine/api',
    AI_URL: '/appengine/tzaip/api/hisp',
    AIPP_URL: '/appengine/api/jober/v1/api',
    MODEL_LIST_URL: `/appengine/api/model_io_manager/v1`,
    PLUGIN_URL: '/appengine/api/jober',
    COLLECT_URL: '/appengine/api/jober/aipp',
    APP_URL: '/appengine/api/jober',
    LOGIN_URL: '/fce',
  },
  gamma: {
    JANE_URL: '/appengine/api',
    AI_URL: '/appengine/tzaip/api/hisp',
    AIPP_URL: '/appengine/api/jober/v1/api',
    MODEL_LIST_URL: `/appengine/api/model_io_manager/v1`,
    PLUGIN_URL: '/appengine/api/jober',
    COLLECT_URL: '/appengine/api/jober/aipp',
    APP_URL: '/appengine/api/jober',
    LOGIN_URL: '/fce',
  },
  beta: {
    JANE_URL: '/appengine/api',
    AI_URL: '/appengine/tzaip/api/hisp',
    AIPP_URL: '/appengine/api/jober/v1/api',
    MODEL_LIST_URL: `/appengine/api/model_io_manager/v1`,
    PLUGIN_URL: '/appengine/api/jober',
    COLLECT_URL: '/appengine/api/jober/aipp',
    APP_URL: '/appengine/api/jober',
    LOGIN_URL: '/fce',
  },
  alpha: {
    JANE_URL: '/appengine/api',
    AI_URL: '/appengine/tzaip/api/hisp',
    AIPP_URL: '/appengine/api/jober/v1/api',
    MODEL_LIST_URL: `/appengine/api/model_io_manager/v1`,
    PLUGIN_URL: '/appengine/api/jober',
    COLLECT_URL: '/appengine/api/jober/aipp',
    APP_URL: '/appengine/api/jober',
    LOGIN_URL: '/fce',
  },
};
