export const httpUrlMap = {
  development: {
    JANE_URL: '/aippApi',
    ELSA_URL: '/else',
    AI_URL: '/aiApi',
    AIPP_URL: '/aippApi',
    KNOWLEDGE_URL: '/api/jober/knowledge',
    ICON_URL: 'https://jane-beta.huawei.com/api',
    PUBLISH_URL: 'https://jane-beta.huawei.com/appbuilder/#',
    WS_URL: 'ws://10.169.58.7:8080/v1/api/aipp/streamLog',
    WS_AUDIO_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/asr',
    MODEL_URL: '/modelApi',
    APP_URL: '/app',
    TOOL_URL: '/toolApi',
    MODEL_LIST_URL: '/v1',
    PLUGIN_URL: '/api/jober',
    MODEL_BASE_URL: 'modelbase',
  },
  production: {
    JANE_URL: 'https://jane.huawei.com/api',
    ELSA_URL: 'https://fit-elsa-prod.lab.huawei.com',
    ICON_URL: 'https://jane.huawei.com/api',
    AI_URL: 'https://tzaip.rnd.huawei.com/tzaip/api/hisp',
    AIPP_URL: 'https://jane.huawei.com/api/jober/v1/api',
    PUBLISH_URL: 'https://jane.huawei.com/appbuilder/#',
    WS_URL: '/v1/api/aipp/streamLog',
    WS_AUDIO_URL: 'wss://tzaip.rnd.huawei.com/tzaip/api/hisp/api/v1/platform/app/asr',
    MODEL_URL: 'https://tzaip-beta.paas.huawei.com/api',
    MODEL_LIST_URL: 'http://model-io-manager:8010/v1',
    PLUGIN_URL: '/api/jober',
    MODEL_BASE_URL: 'modelbase',
  },
  gamma: {
    JANE_URL: 'https://jane-gamma.huawei.com/api',
    ICON_URL: 'https://jane-gamma.huawei.com/api',
    ELSA_URL: 'https://fit-elsa-gamma.lab.huawei.com',
    AI_URL: 'https://tzaip-beta.paas.huawei.com/tzaip/api/hisp',
    AIPP_URL: 'https://jane-gamma.huawei.com/api/jober/v1/api',
    PUBLISH_URL: 'https://jane-gamma.huawei.com/appbuilder/#',
    WS_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/chat',
    WS_AUDIO_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/asr',
    MODEL_URL: 'https://tzaip-beta.paas.huawei.com/api',
    MODEL_LIST_URL: '/v1',
  },
  beta: {
    JANE_URL: 'https://jane-beta.huawei.com/api',
    ICON_URL: 'https://jane-beta.huawei.com/api',
    ELSA_URL: 'https://fit-elsa-alpha.lab.huawei.com',
    AI_URL: 'https://tzaip-beta.paas.huawei.com/tzaip/api/hisp',
    AIPP_URL: 'https://jane-beta.huawei.com/api/jober/v1/api',
    PUBLISH_URL: 'https://jane-beta.huawei.com/appbuilder/#',
    WS_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/chat',
    WS_AUDIO_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/asr',
    MODEL_URL: 'https://tzaip-beta.paas.huawei.com/api',
    MODEL_LIST_URL: '/v1',
  },
  alpha: {
    JANE_URL: 'https://jane-alpha.huawei.com/api',
    ICON_URL: 'https://jane-alpha.huawei.com/api',
    ELSA_URL: 'https://fit-elsa-alpha.lab.huawei.com',
    AI_URL: 'https://tzaip-beta.paas.huawei.com/tzaip/api/hisp',
    PUBLISH_URL: 'https://jane-alpha.huawei.com/appbuilder/#',
    AIPP_URL: 'https://jane-alpha.huawei.com/api/jober/v1/api',
    WS_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/chat',
    WS_AUDIO_URL: 'wss://tzaip-beta.paas.huawei.com/tzaip/api/hisp/api/v1/platform/app/asr',
    MODEL_URL: 'https://tzaip-beta.paas.huawei.com/api',
    MODEL_LIST_URL: '/v1',
  },
};
