/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_FITABLEINSTANCE_C_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_FITABLEINSTANCE_C_H

#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Application_instance/1.0.0/cplusplus/ApplicationInstance.hpp>
#include <component/com_huawei_fit_hakuna_kernel_shared_Fitable/1.0.0/cplusplus/Fitable.hpp>
#include <fit/stl/vector.hpp>
#include <fit/memory/fit_base.hpp>
#include <fit/stl/string.hpp>
#include <fit/stl/map.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace shared {
struct FitableInstance : public FitBase {
    Fit::vector<::fit::hakuna::kernel::registry::shared::ApplicationInstance> applicationInstances {};
    ::fit::hakuna::kernel::shared::Fitable *fitable { nullptr };
    Fit::vector<Fit::string> aliases {};
    Fit::vector<Fit::string> tags {};
    Fit::map<Fit::string, Fit::string> extensions {};
};
}
}
}
}
}

#endif
