/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_CLIENT_REQUESTRESPONSEV4_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_CLIENT_REQUESTRESPONSEV4_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_shared_address/1.0.0/cplusplus/address.hpp>
#include <component/com_huawei_fit_hakuna_kernel_broker_shared_fit_response/1.0.0/cplusplus/fitResponse.hpp>
#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Application/1.0.0/cplusplus/Application.hpp>
#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Worker/1.0.0/cplusplus/Worker.hpp>
#include <fit/stl/string.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace broker {
namespace client {
struct RequestContext {
    /* * 请求超时时间，单位ms */
    int64_t timeout {};
    registry::shared::Worker worker;
    registry::shared::Application application;
};

struct __requestResponseV4 {
    using InType = ::Fit::Framework::ArgumentsIn<const ::fit::hakuna::shared::Address *, const Fit::bytes *,
        const Fit::bytes *, const RequestContext *>;
    using OutType = ::Fit::Framework::ArgumentsOut<::fit::hakuna::kernel::broker::shared::FitResponse **>;
};

/**
 * 调用Fit请求，同步接收一个返回值。
 *
 * @param address 表示请求的地址。
 * @param metadata 表示请求的元数据。
 * @param data 表示请求的业务数据。
 * @param requestContext 表示请求的上下文。
 * @return 表示返回值。
 */
class requestResponseV4
    : public ::Fit::Framework::ProxyClient<FitCode(__requestResponseV4::InType, __requestResponseV4::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "47a8ec8a3d8f46daa1f2d751ad7d6d16";
    requestResponseV4()
        : ::Fit::Framework::ProxyClient<FitCode(__requestResponseV4::InType, __requestResponseV4::OutType)>(GENERIC_ID)
    {}
    ~requestResponseV4() = default;
};
}
}
}
}
}

#endif
