/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_WORKER_C_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_WORKER_C_H

#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Address/1.0.0/cplusplus/Address.hpp>
#include <fit/stl/vector.hpp>
#include <fit/stl/string.hpp>
#include <fit/stl/map.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace shared {
struct Worker : public FitBase {
    Fit::vector<::fit::hakuna::kernel::registry::shared::Address> addresses {};
    // 地址所在进程唯一标识，正常ip网络下可用host:port拼接或uuid作为唯一标识，心跳时进程上报给心跳服务时应使用该标识，用于进程下线时更新对应服务的状态
    Fit::string id {};
    int32_t expire {};
    // 待定，时间段的含义
    Fit::string environment {};
    // 扩展信息
    Fit::map<Fit::string, Fit::string> extensions {};
    // worker version，worker包含数据计算得到worker完整性唯一校验值
    Fit::string version;
};
}
}
}
}
}

#endif
