ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ENV APP_PATH /opt/jane

COPY EulerOS.repo /etc/yum.repos.d/

RUN  yum makecache && \
     yum install -y shadow-utils vi && \
     groupadd -g 1888 -r jane && \
     groupadd -g 2000 -r edatamate && \
     useradd -u 1888 -r -g 1888 -G 2000 -M jane

#安装scc
COPY seccomponent-1.1.8-release.rpm /
RUN rpm -ivh /seccomponent-1.1.8-release.rpm \
    && rm -f /seccomponent-1.1.8-release.rpm \
    && chmod 500 /usr/local/seccomponent -R \
    && chown -R 1888:2000 /usr/local/seccomponent

#镜像仓里的
RUN mkdir -p /opt
RUN mkdir -p $APP_PATH

ARG APP
ENV APP ${APP}
COPY $APP $APP_PATH
COPY start.sh $APP_PATH
RUN chmod +x $APP_PATH/start.sh

RUN ls -l

CMD sh $APP_PATH/start.sh