/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_ENDPOINT_C_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_ENDPOINT_C_H

#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace shared {
struct Endpoint : public FitBase {
    int32_t port {};
    /* *
     * rsocket------0
     * socket-------1
     * http---------2
     * grpc---------3
     * https--------4
     * uc-----------10
     * shareMemory--11
     */
    int32_t protocol {};
};
}
}
}
}
}

#endif