/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FITLAB_MATATA_RULEENGINE_RULE_JSON_EXECUTE_H
#define COM_HUAWEI_FITLAB_MATATA_RULEENGINE_RULE_JSON_EXECUTE_H

#include <fit/external/framework/proxy_client.hpp>

#include <fit/stl/string.hpp>

namespace fitLab {
namespace matata {
namespace ruleEngine {
namespace rule {
namespace json {
struct __execute {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::string *, const Fit::string *, const Fit::string *>;
    using OutType = ::Fit::Framework::ArgumentsOut<Fit::string **>;
};

/**
 * 为规则提供基于JSON参数的实现
 *
 * @param environment 表示待执行的脚本所属的环境。
 * @param id 表示待执行的规则的id。
 * @param parameter 表示执行规则时使用的参数的JSON字符串表现形式。
 * @return 表示执行结果。
 */
class execute : public ::Fit::Framework::ProxyClient<FitCode(__execute::InType, __execute::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "f54d01848ca146d7aa450afe77027ddf";
    execute() : ::Fit::Framework::ProxyClient<FitCode(__execute::InType, __execute::OutType)>(GENERIC_ID) {}
    ~execute() = default;
};
}
}
}
}
}

#endif