/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_SHARED_ADDRESS_H
#define COM_HUAWEI_FIT_HAKUNA_SHARED_ADDRESS_H

#include <fit/stl/string.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace shared {
struct Address : public FitBase {
    /* *
     * 地址所在进程唯一标识，正常ip网络下可用host:ip拼接或uuid作为唯一标识.
     * 心跳时，进程上报给心跳服务时应使用该标识，用于进程下线时更新对应服务的状态.
     */
    Fit::string workerId;
    Fit::string host;
    int32_t port;
};
}
}
}

#endif
