application:
  name: 'jober'

worker:
  id: 'jober-worker'
  environment: 'prod'
  environment-sequence: 'prod'

matata:
  registry:
    host: 'fit-service-registry.huawei.com'
    port: 80
    protocol: 2
    environment: 'prod'

server:
  http:
    port: 8004
    context-path: '/api/jober'
    large-body-size: 104857600

logging:
  level: "INFO"

plugin:
  registry:
    sync:
      period: 15
  heartbeat:
    sync:
      initial-delay: 5
      period: 5
      alive-time: 30
  security-kms:
    his:
      app-id: 'com.huawei.ipd.tianzhou.framework'
      kms:
        env: 'pro'
  fit-sso-filter-his:
    debug: false
    exclude: /api/jober/health
    access-key: 2X1X2023080321220040PMdwf7HsYlxgCAlHHJpK6ep1qXgwfFSnP5sx5Ejg0MdAADONsAij9onrEOWVSCJtAwyTuHgf8j/BRVfDsg8LrZD35HRk96172DYITP0qeK90JMsuKcgkLMsX+Fj5qgNKqCXsQvm2+IiCG5mxCeYey4roRe8DfM7lbA==
    secret-access-key: 2X1X2023080321220040PMdwf7HsYlxgCAlHHJpK6ep1qXgwfFSnP5sx5Ejg0MdAADONsAij9onrEOWVSCJtAwzJxF0UmYRAYNvfm36lH/o2zhmMgI4VTPmBRbijbQpXXnKX5HJArdw562rL5YJ3bPJqMMuK/pA5WkDl838h2P0gTYFLdGNvA2QruIf69e972MQtdDXw+7YNLRwfNg==
    conf-url: https://idaas.huawei.com/pubconf/config/client/v1/sdkconf
    sign-key:
      jane: '2X1X2023090709465340oWO1E9VNioUqOnfMrTXnDhO5Z4DsIHXmgGdVjU6b+FnYvOwg25vbeG7f/K8ISN1UAwxb8ahD2taRkju+pEdHLb5O+dO48c5P4NftxLIDcBkzRB78pW4='