application:
  name: 'jober'

worker:
  id: 'jober-worker'
  environment: 'alpha'
  environment-sequence: 'alpha'

matata:
  registry:
    host: 'fit-service-registry-alpha.huawei.com'
    port: 80
    protocol: 2
    environment: 'alpha'

server:
  http:
    port: 8003
    context-path: '/api/jober'
    large-body-size: 104857600

logging:
  level: "INFO"

plugin:
  security-kms:
    his:
      app-id: 'com.huawei.ipd.tianzhou.framework'
      kms:
        env: 'beta'
  fit-sso-filter-his:
    debug: false
    exclude: /api/jober/health,/api/jober/v3/openapi,/**/*.*,/api/jober/v1/*/cookie
    access-key: 2X1X2023080120315040GIW3G7aMGsoYOqmiJbD5Mml3tcDdkxS8QIi4JaAFhl2SKM4SyGj2qnSa35uCi1dzAwxRKrvVa83pXoufHQouzfUPMcbba7asclELGp50MbBagZ4KJD3I+AxVE7x/+U4DJr7qr44IyQIswDzfC/jCC/5cRGGmGS6/oQ==
    secret-access-key: 2X1X2023080120315040GIW3G7aMGsoYOqmiJbD5Mml3tcDdkxS8QIi4JaAFhl2SKM4SyGj2qnSa35uCi1dzAwyvHu8no1o22Y4/mCC2LzwpprQ456l0OUerrtm3OtEXK3u9JvKJN1dVQIe6ZmBBzVxK5Qr2fctk5ilw/us99Ox7U42EymdgSvJeTbiVk8p/3+RuKKbuatB9xEXKXA==
    conf-url: https://uniportal-beta.huawei.com/pubconf/config/client/v1/sdkconf
    sign-key:
      jane: '2X1X2023090610210840otVY2J1+3ubJsToRqSs3NqW44yvYVaO5IZ+qQdAuNt+3sxNSiaUQhyl5MMWl+2YVAwyoJT3c0tv0UoNKfF8KPRCukMStUjkcFSa99psRYn+IMWqjwY4='