/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_MATATA_CONF_SUBSCRIPTION_CLIENT_REMOVE_H
#define COM_HUAWEI_MATATA_CONF_SUBSCRIPTION_CLIENT_REMOVE_H

#include <fit/external/framework/proxy_client.hpp>

#include <fit/stl/string.hpp>
#include <fit/stl/vector.hpp>

namespace matata {
namespace conf {
namespace subscription {
namespace client {
struct __remove {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::string *, const Fit::vector<Fit::string> *>;
};

/**
 * 将配置路径从订阅组中移除。
 *
 * @param subscription 表示待移除配置路径的订阅组的名称的字符串。
 * @param paths 表示待从订阅组中移除的配置路径的集合。
 */
class remove : public ::Fit::Framework::ProxyClient<FitCode(__remove::InType)> {
public:
    static constexpr const char *GENERIC_ID = "6f93d3c984ed4fdf9afd49e666779831";
    remove() : ::Fit::Framework::ProxyClient<FitCode(__remove::InType)>(GENERIC_ID) {}
    ~remove() = default;
};
}
}
}
}

#endif
