delete
from store_tool_group;

INSERT INTO store_tool_group ("name", "summary", "description", "extensions", "definition_group_name")
VALUES ('depth-estimation-group-name',
        'depth-estimation-summary',
        'depth-estimation-description',
        '{"name": "depth-estimation-def", "description": "Depth estimation is the task of predicting depth of the objects present in an image.", "parameters": {"type": "object", "properties": {"taskId": {"description": "taskId", "type": "string"}, "model": {"description": "模型", "type": "string"}, "images": {"description": "输入的图像，可以是指向图像的 HTTP 链接或本地路径。管道接受单个图像或图像批次，批次中的图像必须全部采用相同格式。", "type": "string"}, "timeout": {"description": "从网络获取图像的最大等待时间（以秒为单位）。如果为 None，则不设置超时，调用可能会永远阻塞。", "type": "number"}}, "required": ["taskId", "model", "images"], "order": ["taskId", "model", "images", "timeout"]}, "return": {"type": "object", "properties": {"predicted_depth": {"type": "object", "description": "模型预测的深度，作为`torch.Tensor`类型", "additionalProperties": true}, "depth": {"type": "object", "description": "模型预测的深度，作为`PIL.Image`类型的图像", "additionalProperties": true}}, "required": ["predicted_depth", "depth"]}}',
        'depth-estimation-definition-group-name');

INSERT INTO store_tool_group ("name", "summary", "description", "extensions", "definition_group_name")
VALUES ('image-to-image-group-name',
        'image-to-image-summary',
        'image-to-image-description',
        '{"name": "image-to-image-def", "description": "Image-to-image is the task of transforming a source image to match the characteristics of a target image or a target image domain. Any image manipulation and enhancement is possible with image to image models.", "parameters": {"type": "object", "properties": {"taskId": {"description": "taskId", "type": "string"}, "model": {"description": "模型", "type": "string"}, "prompt": {"description": "用于指导模型生成图像的引导词。", "type": "string"}, "image": {"description": "输入的图像，可以是指向图像的 HTTP 链接或本地路径。", "type": "string"}, "negative_prompt": {"description": "用于指导模型不要在生成图像中包含某些内容的引导词。", "type": "string"}, "num_images_per_prompt ": {"description": "生成图像的数量", "type": "integer", "default": 1}, "num_inference_steps  ": {"description": "模型去噪迭代次数，增加去噪次数会增加生成图像的质量，但同时也增加推理时间", "type": "integer", "default": 50}}, "required": ["taskId", "model", "prompt", "image"], "order": ["taskId", "model", "prompt", "image", "negative_prompt", "num_images_per_prompt ", "num_inference_steps  "]}, "return": {"type": "array", "items": {"description": "返回的结果是图像列表。", "type": "object", "properties": {"data": {"description": "处理后的图像base64编码，作为PIL Image。", "type": "string", "contentEncoding": "base64"}, "mime": {"description": "图像格式，如image/png", "type": "string"}}, "required": ["data", "mime"]}}}',
        'image-to-image-definition-group-name');

INSERT INTO store_tool_group ("name", "summary", "description", "extensions", "definition_group_name")
VALUES ('automatic-speech-recognition-group-name',
        'automatic-speech-recognition-summary',
        'automatic-speech-recognition-description',
        '{"name": "automatic-speech-recognition-def", "description": "Automatic Speech Recognition (ASR), also known as Speech to Text (STT), is the task of transcribing a given audio to text. It has many applications, such as voice user interfaces.", "parameters": {"type": "object", "properties": {"taskId": {"description": "taskId", "type": "string"}, "model": {"description": "模型", "type": "string"}, "inputs": {"description": "输入内容，可以是本地音频文件的文件名或公共 URL 地址。文件将以正确的采样率读取以获得波形，需要在系统中安装 ffmpeg。", "type": "string"}, "return_timestamps": {"description": "仅适用于纯 CTC 模型（如 Wav2Vec2, HuBERT 等）和 Whisper 模型。对于 CTC 模型，时间戳可以为 \"char\" 或 \"word\" 格式。对于 Whisper 模型，时间戳可以为 \"word\" 或 True。", "type": "boolean"}, "generate_kwargs": {"description": "用于生成调用的 `generate_config` 的临时参数字典。有关生成的完整概述，请参阅以下指南。https://huggingface.co/docs/transformers/en/main_classes/text_generation", "type": "object", "additionalProperties": true}, "max_new_tokens": {"description": "生成的最大令牌数，不包括提示中的令牌数。", "type": "integer"}}, "required": ["taskId", "model", "inputs"], "order": ["taskId", "model", "inputs", "return_timestamps", "generate_kwargs", "max_new_tokens"]}, "return": {"type": "object", "properties": {"text": {"description": "识别的文本。", "type": "string"}, "chunks": {"description": "当使用 `return_timestamps` 时，`chunks` 将成为一个包含模型识别的各种文本块的列表。", "type": "array", "items": {"type": "object", "properties": {"text": {"description": "文本块。", "type": "string"}, "timestamp": {"description": "文本块的时间戳。", "type": "array", "items": {"type": "number"}, "minItems": 2, "maxItems": 2}}, "required": ["text", "timestamp"]}}}, "required": ["text"]}}',
        'automatic-speech-recognition-definition-group-name');

INSERT INTO store_tool_group ("name", "summary", "description", "extensions", "definition_group_name")
VALUES ('automatic-speech-recognition2-group-name',
        'automatic-speech-recognition-group-name-summary',
        'automatic-speech-recognition-group-name-description',
        '{"name": "automatic-speech-recognition2-def", "add": "text", "description": "Automatic Speech Recognition (ASR), also known as Speech to Text (STT), is the task of transcribing a given audio to text. It has many applications, such as voice user interfaces.", "parameters": {"type": "object", "properties": {"taskId": {"description": "taskId", "type": "string"}, "model": {"description": "模型", "type": "string"}, "inputs": {"description": "输入内容，可以是本地音频文件的文件名或公共 URL 地址。文件将以正确的采样率读取以获得波形，需要在系统中安装 ffmpeg。", "type": "string"}, "return_timestamps": {"description": "仅适用于纯 CTC 模型（如 Wav2Vec2, HuBERT 等）和 Whisper 模型。对于 CTC 模型，时间戳可以为 \"char\" 或 \"word\" 格式。对于 Whisper 模型，时间戳可以为 \"word\" 或 True。", "type": "boolean"}, "generate_kwargs": {"description": "用于生成调用的 `generate_config` 的临时参数字典。有关生成的完整概述，请参阅以下指南。https://huggingface.co/docs/transformers/en/main_classes/text_generation", "type": "object", "additionalProperties": true}, "max_new_tokens": {"description": "生成的最大令牌数，不包括提示中的令牌数。", "type": "integer"}}, "required": ["taskId", "model", "inputs"], "order": ["taskId", "model", "inputs", "return_timestamps", "generate_kwargs", "max_new_tokens"]}, "return": {"type": "object", "properties": {"text": {"description": "识别的文本。", "type": "string"}, "chunks": {"description": "当使用 `return_timestamps` 时，`chunks` 将成为一个包含模型识别的各种文本块的列表。", "type": "array", "items": {"type": "object", "properties": {"text": {"description": "文本块。", "type": "string"}, "timestamp": {"description": "文本块的时间戳。", "type": "array", "items": {"type": "number"}, "minItems": 2, "maxItems": 2}}, "required": ["text", "timestamp"]}}}, "required": ["text"]}}',
        'automatic-speech-recognition2-definition-group-name');
