/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_UNSUBSCRIBEFITABLES_G_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_UNSUBSCRIBEFITABLES_G_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_kernel_shared_Fitable/1.0.0/cplusplus/Fitable.hpp>
#include <fit/stl/vector.hpp>
#include <fit/stl/string.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace server {
struct __unsubscribeFitables {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::vector<::fit::hakuna::kernel::shared::Fitable> *,
        const Fit::string *, const Fit::string *>;
};

/**
 * @param fitables
 * @param workerId
 * @param callbackFitableId
 */
class unsubscribeFitables : public ::Fit::Framework::ProxyClient<FitCode(__unsubscribeFitables::InType)> {
public:
    static constexpr const char *GENERIC_ID = "087994fc907b4f76b9f9b2a62e07ef2c";
    unsubscribeFitables() : ::Fit::Framework::ProxyClient<FitCode(__unsubscribeFitables::InType)>(GENERIC_ID) {}
    explicit unsubscribeFitables(ContextObj ctx)
        : ::Fit::Framework::ProxyClient<FitCode(__unsubscribeFitables::InType)>(GENERIC_ID, ctx)
    {}
    ~unsubscribeFitables() = default;
};
}
}
}
}
}

#endif