/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_REMOVERESGITRYADDRESS_G_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_REMOVERESGITRYADDRESS_G_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_registry_registry_common/1.0.0/cplusplus/registryCommon.hpp>
namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace server {
struct __removeResgitryAddress {
    using InType = ::Fit::Framework::ArgumentsIn<const ::fit::registry::Address *>;
    using OutType = ::Fit::Framework::ArgumentsOut<int32_t **>;
};

/**
 * @param address
 * @return
 */
class removeResgitryAddress
    : public ::Fit::Framework::ProxyClient<FitCode(__removeResgitryAddress::InType, __removeResgitryAddress::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "33a95d85e79b44f3afb5075603d5c8fb";
    removeResgitryAddress()
        : ::Fit::Framework::ProxyClient<FitCode(__removeResgitryAddress::InType, __removeResgitryAddress::OutType)>(
        GENERIC_ID)
    {}
    explicit removeResgitryAddress(ContextObj ctx)
        : ::Fit::Framework::ProxyClient<FitCode(__removeResgitryAddress::InType, __removeResgitryAddress::OutType)>(
        GENERIC_ID, ctx)
    {}
    ~removeResgitryAddress() = default;
};
}
}
}
}
}

#endif
