# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ApplyPermissionMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ApplyPermissionMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsApplyPermissionMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ApplyPermissionMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ApplyPermissionMessage
    def Permission(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ApplyPermissionMessage
    def ObjectKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ApplyPermissionMessage
    def MemoryKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ApplyPermissionMessageStart(builder):
    builder.StartObject(3)

def Start(builder):
    ApplyPermissionMessageStart(builder)

def ApplyPermissionMessageAddPermission(builder, permission):
    builder.PrependInt8Slot(0, permission, 0)

def AddPermission(builder, permission):
    ApplyPermissionMessageAddPermission(builder, permission)

def ApplyPermissionMessageAddObjectKey(builder, objectKey):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(objectKey), 0)

def AddObjectKey(builder, objectKey):
    ApplyPermissionMessageAddObjectKey(builder, objectKey)

def ApplyPermissionMessageAddMemoryKey(builder, memoryKey):
    builder.PrependInt32Slot(2, memoryKey, 0)

def AddMemoryKey(builder, memoryKey):
    ApplyPermissionMessageAddMemoryKey(builder, memoryKey)

def ApplyPermissionMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return ApplyPermissionMessageEnd(builder)
