# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

class ErrorType(object):
    None_ = 0
    NotConnectedToDataBus = 1
    DataBusDisconnected = 2
    OutOfMemory = 3
    PermissionDenied = 4
    Timeout = 5
    IllegalMessageHeader = 6
    IllegalMessageBody = 7
    MallocFailed = 8
    KeyNotFound = 9
    MemoryNotFound = 10
    MemoryReadError = 11
    MemoryWriteError = 12
    UnknownPermissionType = 13
    DuplicatePermitApplication = 14
    IllegalStateForPermitRelease = 15
    IOOutOfBounds = 16
    UnknownError = 17
