# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

class ErrorType(object):
    None_ = 0
    NotConnectedToDataBus = 1
    DataBusDisconnected = 2
    OutOfMemory = 3
    PermissionDenied = 4
    Timeout = 5
    IllegalMessageHeader = 6
    IllegalMessageBody = 7
    MallocFailed = 8
    KeyNotFound = 9
    KeyAlreadyExists = 10
    MemoryNotFound = 11
    MemoryReadError = 12
    MemoryWriteError = 13
    UnknownPermissionType = 14
    DuplicatePermitApplication = 15
    IllegalStateForPermitApplication = 16
    IllegalStateForPermitRelease = 17
    IOOutOfBounds = 18
    PlatformNotSupported = 19
    UnknownError = 127
