# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ErrorMessageResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ErrorMessageResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsErrorMessageResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ErrorMessageResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ErrorMessageResponse
    def ErrorType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def ErrorMessageResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    ErrorMessageResponseStart(builder)

def ErrorMessageResponseAddErrorType(builder, errorType):
    builder.PrependInt8Slot(0, errorType, 0)

def AddErrorType(builder, errorType):
    ErrorMessageResponseAddErrorType(builder, errorType)

def ErrorMessageResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return ErrorMessageResponseEnd(builder)
