# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class GetMetaDataMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetMetaDataMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGetMetaDataMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GetMetaDataMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetMetaDataMessage
    def ObjectKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GetMetaDataMessageStart(builder):
    builder.StartObject(1)

def Start(builder):
    GetMetaDataMessageStart(builder)

def GetMetaDataMessageAddObjectKey(builder, objectKey):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objectKey), 0)

def AddObjectKey(builder, objectKey):
    GetMetaDataMessageAddObjectKey(builder, objectKey)

def GetMetaDataMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return GetMetaDataMessageEnd(builder)
