# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Heartbeat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Heartbeat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHeartbeat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Heartbeat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Heartbeat
    def TimeStamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HeartbeatStart(builder):
    builder.StartObject(1)

def Start(builder):
    HeartbeatStart(builder)

def HeartbeatAddTimeStamp(builder, timeStamp):
    builder.PrependUint32Slot(0, timeStamp, 0)

def AddTimeStamp(builder, timeStamp):
    HeartbeatAddTimeStamp(builder, timeStamp)

def HeartbeatEnd(builder):
    return builder.EndObject()

def End(builder):
    return HeartbeatEnd(builder)
