# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

class MessageType(object):
    Unknown = 0
    Error = 1
    HeartBeat = 16
    RuntimeReport = 17
    ApplyMemory = 32
    ApplyPermission = 33
    ReleasePermission = 48
    ReleaseMemory = 49
    GetMetaData = 65
