# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MessageHeader(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MessageHeader()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMessageHeader(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MessageHeader
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MessageHeader
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # MessageHeader
    def Size(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def MessageHeaderStart(builder):
    builder.StartObject(2)

def Start(builder):
    MessageHeaderStart(builder)

def MessageHeaderAddType(builder, type):
    builder.PrependInt8Slot(0, type, 0)

def AddType(builder, type):
    MessageHeaderAddType(builder, type)

def MessageHeaderAddSize(builder, size):
    builder.PrependUint32Slot(1, size, 0)

def AddSize(builder, size):
    MessageHeaderAddSize(builder, size)

def MessageHeaderEnd(builder):
    return builder.EndObject()

def End(builder):
    return MessageHeaderEnd(builder)
