# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReleasePermissionMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReleasePermissionMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReleasePermissionMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReleasePermissionMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReleasePermissionMessage
    def Permission(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # ReleasePermissionMessage
    def ObjectKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReleasePermissionMessage
    def MemoryKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

def ReleasePermissionMessageStart(builder):
    builder.StartObject(3)

def Start(builder):
    ReleasePermissionMessageStart(builder)

def ReleasePermissionMessageAddPermission(builder, permission):
    builder.PrependInt8Slot(0, permission, 0)

def AddPermission(builder, permission):
    ReleasePermissionMessageAddPermission(builder, permission)

def ReleasePermissionMessageAddObjectKey(builder, objectKey):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(objectKey), 0)

def AddObjectKey(builder, objectKey):
    ReleasePermissionMessageAddObjectKey(builder, objectKey)

def ReleasePermissionMessageAddMemoryKey(builder, memoryKey):
    builder.PrependInt32Slot(2, memoryKey, -1)

def AddMemoryKey(builder, memoryKey):
    ReleasePermissionMessageAddMemoryKey(builder, memoryKey)

def ReleasePermissionMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReleasePermissionMessageEnd(builder)
