# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Common

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReleaseMemoryMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReleaseMemoryMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReleaseMemoryMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReleaseMemoryMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReleaseMemoryMessage
    def ObjectKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ReleaseMemoryMessage
    def MemoryKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ReleaseMemoryMessageStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReleaseMemoryMessageStart(builder)

def ReleaseMemoryMessageAddObjectKey(builder, objectKey):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objectKey), 0)

def AddObjectKey(builder, objectKey):
    ReleaseMemoryMessageAddObjectKey(builder, objectKey)

def ReleaseMemoryMessageAddMemoryKey(builder, memoryKey):
    builder.PrependInt32Slot(1, memoryKey, 0)

def AddMemoryKey(builder, memoryKey):
    ReleaseMemoryMessageAddMemoryKey(builder, memoryKey)

def ReleaseMemoryMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReleaseMemoryMessageEnd(builder)
