/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_CLIENT_REQUESTRESPONSEV5_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_CLIENT_REQUESTRESPONSEV5_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_shared_address/1.0.0/cplusplus/address.hpp>
#include <component/com_huawei_fit_hakuna_kernel_broker_shared_fit_response_v2/1.0.0/cplusplus/fitResponseV2.hpp>
#include <component/com_huawei_fit_hakuna_kernel_broker_shared_fit_metadata/1.0.0/cplusplus/fitMetaData.hpp>
#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Application/1.0.0/cplusplus/Application.hpp>
#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Worker/1.0.0/cplusplus/Worker.hpp>
#include <fit/stl/string.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace broker {
namespace client {
struct RequestParam {
    /* * 请求超时时间，单位ms */
    int64_t timeout {};
    ::fit::hakuna::shared::Address address;
    fit::hakuna::kernel::broker::shared::MetaData metaData;
    Fit::bytes data;
    registry::shared::Worker worker;
    registry::shared::Application application;
};

struct __requestResponseV5 {
    using InType = ::Fit::Framework::ArgumentsIn<const RequestParam *>;
    using OutType = ::Fit::Framework::ArgumentsOut<::fit::hakuna::kernel::broker::shared::FitResponseV2 **>;
};

/**
 * 调用Fit请求，同步接收一个返回值。
 *
 * @param address 表示请求的地址。
 * @param metadata 表示请求的元数据。
 * @param data 表示请求的业务数据。
 * @param requestContext 表示请求的上下文。
 * @return 表示返回值。
 */
class requestResponseV5
    : public ::Fit::Framework::ProxyClient<FitCode(__requestResponseV5::InType, __requestResponseV5::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "6d850898ee6244f8806b7a4be3aa4d8e";
    requestResponseV5()
        : ::Fit::Framework::ProxyClient<FitCode(__requestResponseV5::InType, __requestResponseV5::OutType)>(GENERIC_ID)
    {}
    ~requestResponseV5() = default;
};
}
}
}
}
}

#endif
