/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_UNREGISTERFITABLES_G_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_UNREGISTERFITABLES_G_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_kernel_shared_Fitable/1.0.0/cplusplus/Fitable.hpp>
#include <fit/stl/vector.hpp>
#include <fit/stl/string.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace server {
struct __unregisterFitables {
    using InType =
        ::Fit::Framework::ArgumentsIn<const Fit::vector<::fit::hakuna::kernel::shared::Fitable> *, const Fit::string *>;
};

/**
 * @param fitables
 * @param workerId
 */
class unregisterFitables : public ::Fit::Framework::ProxyClient<FitCode(__unregisterFitables::InType)> {
public:
    static constexpr const char *GENERIC_ID = "c02af9dafb5b4a609f8c586a8e884710";
    unregisterFitables() : ::Fit::Framework::ProxyClient<FitCode(__unregisterFitables::InType)>(GENERIC_ID) {}
    explicit unregisterFitables(ContextObj ctx)
        : ::Fit::Framework::ProxyClient<FitCode(__unregisterFitables::InType)>(GENERIC_ID, ctx)
    {}
    ~unregisterFitables() = default;
};
}
}
}
}
}

#endif