mybatis:
  mapper-locations: mapper/*Mapper.xml

fit:
  beans:
    packages:
      - 'com.huawei.fit.jober'
      - 'com.huawei.fitframework'
      - 'com.huawei.fit.integration'
  messages:
    basename: i18n/messages

forest:
  interface-package: com.huawei.fit.jober.taskcenter.gateway

jane:
  flowsEngine:
    retry:
      scheduleRate: 60000

distributed-lock-provider: databaseDistributedLockProvider