elsa:
  endpoint: https://fit-elsa-alpha.lab.huawei.com
  accessKey: a90ae902e83540b3b69ceeec38ea0468

jane:
  endpoint: https://jane-alpha.huawei.com
  taskTypeId: e53a9e917b314096ae8808914825d810
  targetUrl:
    whiteList: 任务,审批任务,repoDMS审批任务,需求,质量要求类,交付件写作类
    noSource: 需求
  default:
    template:
      id: 4f91b69973d1453aadf384d508aed894

corsfilter:
  priority: 50
  patterns: "/**"
  origin: "https://tianzhou-alpha.huawei.com"

a3000:
  tenantId: 4b1f59a7ccdd4faf930f29b4f1f946b3
  ownTrace: false
  useLimit: false
  limit: 5
  operator: com.huawei.a3000