mybatis:
  mapper-locations: mapper/*Mapper.xml

fit:
  beans:
    packages:
      - 'modelengine.fit.jober'
      - 'modelengine.fitframework'
      - 'modelengine.fit.integration'
  messages:
    basename: i18n/messages

forest:
  interface-package: modelengine.fit.jober.taskcenter.gateway

jane:
  flowsEngine:
    retry:
      scheduleRate: 60000

distributed-lock-provider: databaseDistributedLockProvider