jane:
  endpoint:
  targetUrl:
    noSource: 需求
  default:
    template:
      id:
  useDataEngine: false

corsfilter:
  priority:
  patterns:
  origin: jade.huawei.com

a3000:
  tenantId:
  ownTrace: false
  useLimit: true
  limit: 2
  operator: