/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_APPLICATIONINSTANCE_C_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_APPLICATIONINSTANCE_C_H

#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Application/1.0.0/cplusplus/Application.hpp>
#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Worker/1.0.0/cplusplus/Worker.hpp>
#include <fit/stl/vector.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace shared {
struct ApplicationInstance : public FitBase {
    Fit::vector<::fit::hakuna::kernel::registry::shared::Worker> workers {};
    ::fit::hakuna::kernel::registry::shared::Application *application { nullptr };
    /* *
     * protobuf-----0
     * json------1
     */
    Fit::vector<int32_t> formats {};
};
}
}
}
}
}

#endif
