/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_SUBSCRIBEFITABLES_G_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_SUBSCRIBEFITABLES_G_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Fitable_instance/1.0.0/cplusplus/FitableInstance.hpp>
#include <component/com_huawei_fit_hakuna_kernel_shared_Fitable/1.0.0/cplusplus/Fitable.hpp>
#include <fit/stl/vector.hpp>
#include <fit/stl/string.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace server {
struct __subscribeFitables {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::vector<::fit::hakuna::kernel::shared::Fitable> *,
        const Fit::string *, const Fit::string *>;
    using OutType =
        ::Fit::Framework::ArgumentsOut<Fit::vector<::fit::hakuna::kernel::registry::shared::FitableInstance> **>;
};

/**
 * @param fitables
 * @param workerId
 * @param callbackFitableId
 * @return
 */
class subscribeFitables
    : public ::Fit::Framework::ProxyClient<FitCode(__subscribeFitables::InType, __subscribeFitables::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "c9aa580f3fa845c99c2c6145a0499e45";
    subscribeFitables()
        : ::Fit::Framework::ProxyClient<FitCode(__subscribeFitables::InType, __subscribeFitables::OutType)>(GENERIC_ID)
    {}
    explicit subscribeFitables(ContextObj ctx)
        : ::Fit::Framework::ProxyClient<FitCode(__subscribeFitables::InType, __subscribeFitables::OutType)>(GENERIC_ID,
        ctx)
    {}
    ~subscribeFitables() = default;
};
}
}
}
}
}

#endif
