/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_MATATA_NOTIFICATION_CLIENT_PUBLISH_H
#define COM_HUAWEI_MATATA_NOTIFICATION_CLIENT_PUBLISH_H

#include <fit/external/framework/proxy_client.hpp>

#include <fit/stl/string.hpp>

namespace matata {
namespace notification {
namespace client {
struct __publish {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::string *, const Fit::bytes *>;
};

/**
 * 发布通知。
 *
 * @param topic 表示通知的主题。
 * @param data 表示通知的内容。
 */
class publish : public ::Fit::Framework::ProxyClient<FitCode(__publish::InType)> {
public:
    static constexpr const char *GENERIC_ID = "d7dab744dbb54afd9e755c7124b3b77f";
    publish() : ::Fit::Framework::ProxyClient<FitCode(__publish::InType)>(GENERIC_ID) {}
    ~publish() = default;
};
}
}
}

#endif
