fit:
  beans:
    packages:
    - 'com.huawei.jade.store'
druid:
  driver-class-name: org.postgresql.Driver
  initialSize: 5
  minIdle: 5
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  url: jdbc:postgresql://10.91.144.220:5432/for_kms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
  username: enc(2X1X2023062715452540UnHhV4CE5IJHfsfJOWj0mz6VDYS48BmxVKT3hT+jQEpRynHpkOkIobu7l+2CVIRIAwwa8P2t8Jr2BNGB/6o2fDAQ5IqzLejrJGF6zlbL8D6Jyw==)
  password: enc(2X1X2023062715452540UnHhV4CE5IJHfsfJOWj0mz6VDYS48BmxVKT3hT+jQEpRynHpkOkIobu7l+2CVIRIAwwDrd+U1P3sz3rfW8Ndohqze4ZAvzhNuHOxrQtwuBd3A3xR9y1s)
mybatis:
  mapper-locations: 'mapper/*Mapper.xml'
