/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_APPLICATION_C_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_APPLICATION_C_H

#include <fit/stl/string.hpp>
#include <fit/stl/map.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace shared {
struct Application : public FitBase {
    Fit::string name {};
    Fit::string nameVersion {};
    Fit::map<Fit::string, Fit::string> extensions {};
};
}
}
}
}
}

#endif