/*
* Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
* Description:
* Author: auto generated by FIT IDL
* Date:
*/
#include <fit/external/framework/annotation/fitable_registrar.hpp>
#include <genericable/com_huawei_fit_hakuna_kernel_registry_server_query_fitables_addresses/1.0.0/cplusplus/queryFitablesAddresses.hpp>
#include <fit/fit_log.h>
#include <fit/stl/unordered_map.hpp>
#include <registry_server_memory/common/util.h>
#include <registry_server_memory/common/registry_common_converter.hpp>
#include "core/fit_registry_mgr.h"

using namespace Fit;
using namespace Fit::Registry;
namespace {
/**
 * @param fitables
 * @param workerId
 * @return
 */
FitCode QueryFitablesAddresses(ContextObj ctx,
    const Fit::vector<::fit::hakuna::kernel::shared::Fitable> *fitables,
    const Fit::string *workerId,
    Fit::vector<::fit::hakuna::kernel::registry::shared::FitableInstance> **result)
{
    if (fitables == nullptr || workerId == nullptr) {
        FIT_LOG_ERROR("%s", "Null fitables, workerId.");
        return FIT_ERR_PARAM;
    }

    auto resultTemp
        = Fit::Context::NewObj<Fit::vector<::fit::hakuna::kernel::registry::shared::FitableInstance>>(ctx);
    for (const auto &fitable : *fitables) {
        fit_fitable_key_t key;
        key.generic_id = fitable.genericableId;
        key.generic_version = fitable.genericableVersion;
        key.fitable_id = fitable.fitableId;
        CompatibleJavaRegistry(key);
        auto services = Fit::Registry::fit_registry_mgr::instance()->get_registry_service().get_services(key);
        FIT_LOG_DEBUG("Query fitable=(%s:%s), size=%ld.", fitable.genericableId.c_str(),
            fitable.fitableId.c_str(), services.size());
        resultTemp->emplace_back(Aggregate(fitable, services, ctx));
    }
    *result = resultTemp;
    return FIT_ERR_SUCCESS;
}

FIT_REGISTRATIONS
{
    ::Fit::Framework::Annotation::Fitable(::QueryFitablesAddresses)
        .SetGenericId(fit::hakuna::kernel::registry::server::queryFitablesAddresses::GENERIC_ID)
        .SetFitableId("5807f06a3a704708b264ea3c6cfbbd53");
}
} // LCOV_EXCL_LINE