/*
* Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
* Description:
* Author: auto generated by FIT IDL
* Date:
*/

#include <fit/external/framework/annotation/fitable_registrar.hpp>
#include <genericable/com_huawei_fit_hakuna_kernel_registry_server_unregister_fitables/1.0.0/cplusplus/unregisterFitables.hpp>
#include <fit/fit_log.h>
#include "core/fit_registry_mgr.h"
namespace {
/**
 * @param fitables
 * @param workerId
 */
FitCode UnregisterFitables(ContextObj ctx,
    const Fit::vector<::fit::hakuna::kernel::shared::Fitable> *fitables,
    const Fit::string *workerId)
{
    FIT_LOG_CORE("UnregisterFitService enter.");
    if (fitables == nullptr || workerId == nullptr) {
        FIT_LOG_ERROR("UnregisterFitService param is null.");
        return FIT_ERR_PARAM;
    }

    Fit::fit_address addressTemp;
    addressTemp.id = *workerId;

    fit_service_instance_set innerServices;
    for (const auto& it : *fitables) {
        fit_service_instance_t innerService {};
        Fit::fitable_id fitableId;
        fitableId.generic_id = it.genericableId;
        fitableId.generic_version = it.genericableVersion;
        fitableId.fitable_id = it.fitableId;
        fitableId.fitable_version = it.fitableVersion;
        innerService.fitable = fitableId;
        innerService.addresses.emplace_back(addressTemp);
        innerServices.push_back(innerService);
    }

    fit_worker_info_t innerWorker;
    innerWorker.address = addressTemp;
    innerWorker.token = *workerId;
    innerWorker.id = *workerId;
    if (!Fit::Registry::fit_registry_mgr::instance()->get_registry_service() // LCOV_EXCL_BR_LINE
        .unregister_services(innerServices, innerWorker)) { // LCOV_EXCL_BR_LINE
        FIT_LOG_ERROR("UnregisterFitService failed.");
        return FIT_ERR_FAIL;
    }
    FIT_LOG_CORE("UnregisterFitService.");
    return FIT_ERR_SUCCESS;
}

FIT_REGISTRATIONS
{
    ::Fit::Framework::Annotation::Fitable(::UnregisterFitables)
        .SetGenericId(fit::hakuna::kernel::registry::server::unregisterFitables::GENERIC_ID)
        .SetFitableId("0bf2ea00438246a795ad6c1eddf3a77a");
}
} // LCOV_EXCL_LINE