/*
* Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
* Description:
* Author: auto generated by FIT IDL
* Date:
*/

#include <fit/external/framework/annotation/fitable_registrar.hpp>
#include <genericable/com_huawei_fit_hakuna_kernel_registry_server_unsubscribe_fitables/1.0.0/cplusplus/unsubscribeFitables.hpp>
#include <fit/fit_code.h>
#include <fit/fit_log.h>
#include "core/fit_registry_mgr.h"
namespace {
/**
 * @param fitables
 * @param workerId
 * @param callbackFitableId
 */
FitCode UnsubscribeFitables(ContextObj ctx,
    const Fit::vector<::fit::hakuna::kernel::shared::Fitable> *fitables,
    const Fit::string *workerId,
    const Fit::string *callbackFitableId)
{
    FIT_LOG_CORE("UnsubscribeFitService enter.");
    if (fitables == nullptr || workerId == nullptr || callbackFitableId == nullptr) {
        FIT_LOG_ERROR("UnregisterFitService param is null.");
        return FIT_ERR_PARAM;
    }

    Fit::fit_address innerAddress;
    innerAddress.id = *workerId;

    for (const auto& it : *fitables) {
        fit_fitable_key_t fitableKey;
        fitableKey.generic_id = it.genericableId;
        fitableKey.generic_version = it.genericableVersion;
        fitableKey.fitable_id = it.fitableId;

        fit_listener_info_t fitableListenerInfo;
        fitableListenerInfo.address = innerAddress;
        fitableListenerInfo.fitable_id = *callbackFitableId;
        int32_t result = Fit::Registry::fit_registry_mgr::instance()->get_subscription_service()
            .remove_subscription_entry(fitableKey, fitableListenerInfo);
        if (result != FIT_ERR_SUCCESS) {
            FIT_LOG_ERROR("UnsubscribeFitService failed, fitable id is %s, generiable info is %s:%s",
                it.fitableId.c_str(),
                it.genericableId.c_str(),
                it.genericableVersion.c_str());
            return FIT_ERR_FAIL;
        }
    }
    FIT_LOG_CORE("UnsubscribeFitService.");
    return FIT_ERR_SUCCESS;
}

FIT_REGISTRATIONS
{
    ::Fit::Framework::Annotation::Fitable(::UnsubscribeFitables)
        .SetGenericId(fit::hakuna::kernel::registry::server::unsubscribeFitables::GENERIC_ID)
        .SetFitableId("cd617ec49bbc4f04ac1a39d4a6ce0e7b");
}
} // LCOV_EXCL_LINE