mybatis:
  mapper-locations: mapper/*Mapper.xml

fit:
  beans:
    packages:
      - 'modelengine.fit.waterflow'
      - 'modelengine.fitframework'
      - 'modelengine.fit.integration'
  messages:
    basename: i18n/messages

jane:
  flowsEngine:
    retry:
      scheduleRate: 10000
      maxCount: 0
    isNeedFlowCallbackAdapt: false

distributed-lock-provider: databaseDistributedLockProvider