/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_TRACER_ADDFITABLETRACE_H
#define COM_HUAWEI_FIT_TRACER_ADDFITABLETRACE_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_tracer_Fit_trace/1.0.0/cplusplus/FitTrace.hpp>
namespace fit {
namespace tracer {
struct __addFitableTrace {
    using InType = ::Fit::Framework::ArgumentsIn<const ::fit::tracer::FitableTrace *>;
    using OutType = ::Fit::Framework::ArgumentsOut<bool **>;
};

// 链路追踪工具接口
class addFitableTrace
    : public ::Fit::Framework::ProxyClient<FitCode(__addFitableTrace::InType, __addFitableTrace::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "395fcc31872c42c7964ffa7b902dbad9";
    addFitableTrace()
        : ::Fit::Framework::ProxyClient<FitCode(__addFitableTrace::InType, __addFitableTrace::OutType)>(GENERIC_ID)
    {}
    ~addFitableTrace() = default;
};
}
}

#endif
