/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_TRACER_FITTRACE_H
#define COM_HUAWEI_FIT_TRACER_FITTRACE_H

#include <fit/stl/string.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace tracer {
struct BaseFitTrace : public FitBase {
    uint64_t traceTimestamp {};
    Fit::string traceId {};
    Fit::string span {};
    // 调用类型
    uint32_t traceType {};
    // 主机
    Fit::string host {};
    // 端口
    uint32_t port {};
    Fit::string workerId {};
    // 调用结果，ok/Timeout/ConnectError
    Fit::string resultCode {};
    // 时间花费
    uint32_t timeCost {};
    // 流量类型
    uint32_t flowType {};
    // 阶段
    uint32_t stage {};
};

struct FitableTrace {
    BaseFitTrace *baseFitTrace { nullptr };
    Fit::string genericId {};
    Fit::string genericVersion {};
    Fit::string fitId {};
    Fit::string serviceName {};
    Fit::string targetHost {};
    uint32_t targetPort {};
    // 调用类型  1 本地调用本地  2 本地调用远程  3 远程调用本地
    uint32_t callType {};
    Fit::string fromFitId {};
    // 可信步骤 0: validation, 1: before, 2: process, 3: degredation, 4: after, 5: error
    uint32_t trustStage {};
};
}
}

#endif
