/*---------------------------------------------------------------------------------------------
 *  Copyright (c) 2025 Huawei Technologies Co., Ltd. All rights reserved.
 *  This file is a part of the ModelEngine Project.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

#ifndef MODELENGINE_DATABUS_SDK_CLIENT_JNI_SHAREDMEMORYREADERWRITER_H
#define MODELENGINE_DATABUS_SDK_CLIENT_JNI_SHAREDMEMORYREADERWRITER_H

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class modelengine_databus_sdk_client_jni_SharedMemoryReaderWriter */

#ifndef _Included_modelengine_databus_sdk_client_jni_SharedMemoryReaderWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     modelengine_databus_sdk_client_jni_SharedMemoryReaderWriter
 * Method:    read
 * Signature: (IJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_modelengine_databus_sdk_client_jni_SharedMemoryReaderWriter_read
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     modelengine_databus_sdk_client_jni_SharedMemoryReaderWriter
 * Method:    write
 * Signature: (IJJ[B)J
 */
JNIEXPORT jlong JNICALL Java_modelengine_databus_sdk_client_jni_SharedMemoryReaderWriter_write
  (JNIEnv *, jobject, jint, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
#endif

