/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ApplyMemoryMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ApplyMemoryMessage getRootAsApplyMemoryMessage(ByteBuffer _bb) { return getRootAsApplyMemoryMessage(_bb, new ApplyMemoryMessage()); }
  public static ApplyMemoryMessage getRootAsApplyMemoryMessage(ByteBuffer _bb, ApplyMemoryMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ApplyMemoryMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long memorySize() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createApplyMemoryMessage(FlatBufferBuilder builder,
      long memorySize) {
    builder.startTable(1);
    ApplyMemoryMessage.addMemorySize(builder, memorySize);
    return ApplyMemoryMessage.endApplyMemoryMessage(builder);
  }

  public static void startApplyMemoryMessage(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMemorySize(FlatBufferBuilder builder, long memorySize) { builder.addLong(0, memorySize, 0L); }
  public static int endApplyMemoryMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishApplyMemoryMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedApplyMemoryMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ApplyMemoryMessage get(int j) { return get(new ApplyMemoryMessage(), j); }
    public ApplyMemoryMessage get(ApplyMemoryMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

