/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ApplyPermissionMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ApplyPermissionMessage getRootAsApplyPermissionMessage(ByteBuffer _bb) { return getRootAsApplyPermissionMessage(_bb, new ApplyPermissionMessage()); }
  public static ApplyPermissionMessage getRootAsApplyPermissionMessage(ByteBuffer _bb, ApplyPermissionMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ApplyPermissionMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte permission() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int memoryKey() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createApplyPermissionMessage(FlatBufferBuilder builder,
      byte permission,
      int memoryKey) {
    builder.startTable(2);
    ApplyPermissionMessage.addMemoryKey(builder, memoryKey);
    ApplyPermissionMessage.addPermission(builder, permission);
    return ApplyPermissionMessage.endApplyPermissionMessage(builder);
  }

  public static void startApplyPermissionMessage(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPermission(FlatBufferBuilder builder, byte permission) { builder.addByte(0, permission, 0); }
  public static void addMemoryKey(FlatBufferBuilder builder, int memoryKey) { builder.addInt(1, memoryKey, 0); }
  public static int endApplyPermissionMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishApplyPermissionMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedApplyPermissionMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ApplyPermissionMessage get(int j) { return get(new ApplyPermissionMessage(), j); }
    public ApplyPermissionMessage get(ApplyPermissionMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

