/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ApplyPermissionMessageResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ApplyPermissionMessageResponse getRootAsApplyPermissionMessageResponse(ByteBuffer _bb) { return getRootAsApplyPermissionMessageResponse(_bb, new ApplyPermissionMessageResponse()); }
  public static ApplyPermissionMessageResponse getRootAsApplyPermissionMessageResponse(ByteBuffer _bb, ApplyPermissionMessageResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ApplyPermissionMessageResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte errorType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public boolean granted() { int o = __offset(6); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public int memoryKey() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long memorySize() { int o = __offset(10); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createApplyPermissionMessageResponse(FlatBufferBuilder builder,
      byte errorType,
      boolean granted,
      int memoryKey,
      long memorySize) {
    builder.startTable(4);
    ApplyPermissionMessageResponse.addMemorySize(builder, memorySize);
    ApplyPermissionMessageResponse.addMemoryKey(builder, memoryKey);
    ApplyPermissionMessageResponse.addGranted(builder, granted);
    ApplyPermissionMessageResponse.addErrorType(builder, errorType);
    return ApplyPermissionMessageResponse.endApplyPermissionMessageResponse(builder);
  }

  public static void startApplyPermissionMessageResponse(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addErrorType(FlatBufferBuilder builder, byte errorType) { builder.addByte(0, errorType, 0); }
  public static void addGranted(FlatBufferBuilder builder, boolean granted) { builder.addBoolean(1, granted, false); }
  public static void addMemoryKey(FlatBufferBuilder builder, int memoryKey) { builder.addInt(2, memoryKey, 0); }
  public static void addMemorySize(FlatBufferBuilder builder, long memorySize) { builder.addLong(3, memorySize, 0L); }
  public static int endApplyPermissionMessageResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishApplyPermissionMessageResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedApplyPermissionMessageResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ApplyPermissionMessageResponse get(int j) { return get(new ApplyPermissionMessageResponse(), j); }
    public ApplyPermissionMessageResponse get(ApplyPermissionMessageResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

