// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ApplyPermissionMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ApplyPermissionMessage getRootAsApplyPermissionMessage(ByteBuffer _bb) { return getRootAsApplyPermissionMessage(_bb, new ApplyPermissionMessage()); }
  public static ApplyPermissionMessage getRootAsApplyPermissionMessage(ByteBuffer _bb, ApplyPermissionMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ApplyPermissionMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte permission() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String objectKey() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer objectKeyAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer objectKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int memoryKey() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : -1; }
  public boolean isOperatingUserData() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }
  public byte userData(int j) { int o = __offset(12); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int userDataLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector userDataVector() { return userDataVector(new ByteVector()); }
  public ByteVector userDataVector(ByteVector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer userDataAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer userDataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createApplyPermissionMessage(FlatBufferBuilder builder,
      byte permission,
      int objectKeyOffset,
      int memoryKey,
      boolean isOperatingUserData,
      int userDataOffset) {
    builder.startTable(5);
    ApplyPermissionMessage.addUserData(builder, userDataOffset);
    ApplyPermissionMessage.addMemoryKey(builder, memoryKey);
    ApplyPermissionMessage.addObjectKey(builder, objectKeyOffset);
    ApplyPermissionMessage.addIsOperatingUserData(builder, isOperatingUserData);
    ApplyPermissionMessage.addPermission(builder, permission);
    return ApplyPermissionMessage.endApplyPermissionMessage(builder);
  }

  public static void startApplyPermissionMessage(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addPermission(FlatBufferBuilder builder, byte permission) { builder.addByte(0, permission, 0); }
  public static void addObjectKey(FlatBufferBuilder builder, int objectKeyOffset) { builder.addOffset(1, objectKeyOffset, 0); }
  public static void addMemoryKey(FlatBufferBuilder builder, int memoryKey) { builder.addInt(2, memoryKey, -1); }
  public static void addIsOperatingUserData(FlatBufferBuilder builder, boolean isOperatingUserData) { builder.addBoolean(3, isOperatingUserData, false); }
  public static void addUserData(FlatBufferBuilder builder, int userDataOffset) { builder.addOffset(4, userDataOffset, 0); }
  public static int createUserDataVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createUserDataVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startUserDataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endApplyPermissionMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishApplyPermissionMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedApplyPermissionMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ApplyPermissionMessage get(int j) { return get(new ApplyPermissionMessage(), j); }
    public ApplyPermissionMessage get(ApplyPermissionMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

