/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ApplyMemoryMessageResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ApplyMemoryMessageResponse getRootAsApplyMemoryMessageResponse(ByteBuffer _bb) { return getRootAsApplyMemoryMessageResponse(_bb, new ApplyMemoryMessageResponse()); }
  public static ApplyMemoryMessageResponse getRootAsApplyMemoryMessageResponse(ByteBuffer _bb, ApplyMemoryMessageResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ApplyMemoryMessageResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte errorType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int memoryKey() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public long memorySize() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createApplyMemoryMessageResponse(FlatBufferBuilder builder,
      byte errorType,
      int memoryKey,
      long memorySize) {
    builder.startTable(3);
    ApplyMemoryMessageResponse.addMemorySize(builder, memorySize);
    ApplyMemoryMessageResponse.addMemoryKey(builder, memoryKey);
    ApplyMemoryMessageResponse.addErrorType(builder, errorType);
    return ApplyMemoryMessageResponse.endApplyMemoryMessageResponse(builder);
  }

  public static void startApplyMemoryMessageResponse(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addErrorType(FlatBufferBuilder builder, byte errorType) { builder.addByte(0, errorType, 0); }
  public static void addMemoryKey(FlatBufferBuilder builder, int memoryKey) { builder.addInt(1, memoryKey, 0); }
  public static void addMemorySize(FlatBufferBuilder builder, long memorySize) { builder.addLong(2, memorySize, 0L); }
  public static int endApplyMemoryMessageResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishApplyMemoryMessageResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedApplyMemoryMessageResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ApplyMemoryMessageResponse get(int j) { return get(new ApplyMemoryMessageResponse(), j); }
    public ApplyMemoryMessageResponse get(ApplyMemoryMessageResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

