/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

@SuppressWarnings("unused")
public final class ErrorType {
  private ErrorType() { }
  public static final byte None = 0;
  public static final byte OutOfMemory = 1;
  public static final byte NotConnectedToDataBus = 2;
  public static final byte PermissionDenied = 3;
  public static final byte MemoryNotFound = 4;
  public static final byte Timeout = 5;
  public static final byte DataBusDisconnected = 6;

  public static final String[] names = { "None", "OutOfMemory", "NotConnectedToDataBus", "PermissionDenied", "MemoryNotFound", "Timeout", "DataBusDisconnected", };

  public static String name(int e) { return names[e]; }
}

