/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

@SuppressWarnings("unused")
public final class ErrorType {
  private ErrorType() { }
  public static final byte None = 0;
  public static final byte NotConnectedToDataBus = 1;
  public static final byte DataBusDisconnected = 2;
  public static final byte OutOfMemory = 3;
  public static final byte PermissionDenied = 4;
  public static final byte Timeout = 5;
  public static final byte IllegalMessageHeader = 6;
  public static final byte IllegalMessageBody = 7;
  public static final byte MallocFailed = 8;
  public static final byte MemoryNotFound = 9;
  public static final byte UnknownPermissionType = 10;
  public static final byte DuplicatePermitApplication = 11;
  public static final byte IllegalStateForPermitRelease = 12;
  public static final byte UnknownError = 13;

  public static final String[] names = { "None", "NotConnectedToDataBus", "DataBusDisconnected", "OutOfMemory", "PermissionDenied", "Timeout", "IllegalMessageHeader", "IllegalMessageBody", "MallocFailed", "MemoryNotFound", "UnknownPermissionType", "DuplicatePermitApplication", "IllegalStateForPermitRelease", "UnknownError", };

  public static String name(int e) { return names[e]; }
}

