// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GetMetaDataMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static GetMetaDataMessage getRootAsGetMetaDataMessage(ByteBuffer _bb) { return getRootAsGetMetaDataMessage(_bb, new GetMetaDataMessage()); }
  public static GetMetaDataMessage getRootAsGetMetaDataMessage(ByteBuffer _bb, GetMetaDataMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetMetaDataMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String objectKey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer objectKeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer objectKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createGetMetaDataMessage(FlatBufferBuilder builder,
      int objectKeyOffset) {
    builder.startTable(1);
    GetMetaDataMessage.addObjectKey(builder, objectKeyOffset);
    return GetMetaDataMessage.endGetMetaDataMessage(builder);
  }

  public static void startGetMetaDataMessage(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addObjectKey(FlatBufferBuilder builder, int objectKeyOffset) { builder.addOffset(0, objectKeyOffset, 0); }
  public static int endGetMetaDataMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishGetMetaDataMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedGetMetaDataMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetMetaDataMessage get(int j) { return get(new GetMetaDataMessage(), j); }
    public GetMetaDataMessage get(GetMetaDataMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

