// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class GetUserDataMessageResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static GetUserDataMessageResponse getRootAsGetUserDataMessageResponse(ByteBuffer _bb) { return getRootAsGetUserDataMessageResponse(_bb, new GetUserDataMessageResponse()); }
  public static GetUserDataMessageResponse getRootAsGetUserDataMessageResponse(ByteBuffer _bb, GetUserDataMessageResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public GetUserDataMessageResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte userData(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int userDataLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector userDataVector() { return userDataVector(new ByteVector()); }
  public ByteVector userDataVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer userDataAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer userDataInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createGetUserDataMessageResponse(FlatBufferBuilder builder,
      int userDataOffset) {
    builder.startTable(1);
    GetUserDataMessageResponse.addUserData(builder, userDataOffset);
    return GetUserDataMessageResponse.endGetUserDataMessageResponse(builder);
  }

  public static void startGetUserDataMessageResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addUserData(FlatBufferBuilder builder, int userDataOffset) { builder.addOffset(0, userDataOffset, 0); }
  public static int createUserDataVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createUserDataVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startUserDataVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endGetUserDataMessageResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishGetUserDataMessageResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedGetUserDataMessageResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public GetUserDataMessageResponse get(int j) { return get(new GetUserDataMessageResponse(), j); }
    public GetUserDataMessageResponse get(GetUserDataMessageResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

