/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

@SuppressWarnings("unused")
public final class MessageType {
  private MessageType() { }
  public static final byte Unknown = 0;
  public static final byte Error = 1;
  public static final byte HeartBeat = 16;
  public static final byte RuntimeReport = 17;
  public static final byte ApplyMemory = 32;
  public static final byte ApplyPermission = 33;
  public static final byte ReleasePermission = 48;
  public static final byte ReleaseMemory = 49;
  public static final byte GetUserData = 65;
}

