/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

@SuppressWarnings("unused")
public final class MessageType {
  private MessageType() { }
  public static final byte Unknown = 0;
  public static final byte HeartBeat = 1;
  public static final byte ApplyMemory = 2;
  public static final byte ApplyPermission = 3;

  public static final String[] names = { "Unknown", "HeartBeat", "ApplyMemory", "ApplyPermission", };

  public static String name(int e) { return names[e]; }
}

