/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ReleaseMemoryMessageResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ReleaseMemoryMessageResponse getRootAsReleaseMemoryMessageResponse(ByteBuffer _bb) { return getRootAsReleaseMemoryMessageResponse(_bb, new ReleaseMemoryMessageResponse()); }
  public static ReleaseMemoryMessageResponse getRootAsReleaseMemoryMessageResponse(ByteBuffer _bb, ReleaseMemoryMessageResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ReleaseMemoryMessageResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte errorType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }

  public static int createReleaseMemoryMessageResponse(FlatBufferBuilder builder,
      byte errorType) {
    builder.startTable(1);
    ReleaseMemoryMessageResponse.addErrorType(builder, errorType);
    return ReleaseMemoryMessageResponse.endReleaseMemoryMessageResponse(builder);
  }

  public static void startReleaseMemoryMessageResponse(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addErrorType(FlatBufferBuilder builder, byte errorType) { builder.addByte(0, errorType, 0); }
  public static int endReleaseMemoryMessageResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishReleaseMemoryMessageResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedReleaseMemoryMessageResponseBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ReleaseMemoryMessageResponse get(int j) { return get(new ReleaseMemoryMessageResponse(), j); }
    public ReleaseMemoryMessageResponse get(ReleaseMemoryMessageResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

