/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

// automatically generated by the FlatBuffers compiler, do not modify

package com.huawei.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ReleasePermissionMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ReleasePermissionMessage getRootAsReleasePermissionMessage(ByteBuffer _bb) { return getRootAsReleasePermissionMessage(_bb, new ReleasePermissionMessage()); }
  public static ReleasePermissionMessage getRootAsReleasePermissionMessage(ByteBuffer _bb, ReleasePermissionMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ReleasePermissionMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int memoryKey() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createReleasePermissionMessage(FlatBufferBuilder builder,
      int memoryKey) {
    builder.startTable(1);
    ReleasePermissionMessage.addMemoryKey(builder, memoryKey);
    return ReleasePermissionMessage.endReleasePermissionMessage(builder);
  }

  public static void startReleasePermissionMessage(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addMemoryKey(FlatBufferBuilder builder, int memoryKey) { builder.addInt(0, memoryKey, 0); }
  public static int endReleasePermissionMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishReleasePermissionMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedReleasePermissionMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ReleasePermissionMessage get(int j) { return get(new ReleasePermissionMessage(), j); }
    public ReleasePermissionMessage get(ReleasePermissionMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

