/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_NOTIFYFITABLES_G_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_NOTIFYFITABLES_G_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Fitable_instance/1.0.0/cplusplus/FitableInstance.hpp>
#include <fit/stl/vector.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace server {
struct __notifyFitables {
    using InType =
        ::Fit::Framework::ArgumentsIn<const Fit::vector<::fit::hakuna::kernel::registry::shared::FitableInstance> *>;
};

/**
 * @param fitableInstances
 */
class notifyFitables : public ::Fit::Framework::ProxyClient<FitCode(__notifyFitables::InType)> {
public:
    static constexpr const char *GENERIC_ID = "b69df5e8cbcd4166aa5029602e7a58cf";
    notifyFitables() : ::Fit::Framework::ProxyClient<FitCode(__notifyFitables::InType)>(GENERIC_ID) {}
    explicit notifyFitables(ContextObj ctx) : ::Fit::Framework::ProxyClient<FitCode(__notifyFitables::InType)>(
        GENERIC_ID, ctx)
    {}
    ~notifyFitables() = default;
};
}
}
}
}
}

#endif
