/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_SYSTEM_WORKER_GENERICABLEINFO_H
#define COM_HUAWEI_FIT_HAKUNA_SYSTEM_WORKER_GENERICABLEINFO_H

#include <component/com_huawei_fit_hakuna_system_worker_fitable_info/1.0.0/cplusplus/fitableInfo.hpp>
#include <fit/stl/string.hpp>
#include <fit/stl/vector.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace system {
namespace worker {
/* * 泛服务定义的相关信息。 */
struct GenericableInfo : public FitBase {
    /* * 表示泛服务定义的唯一标识。 */
    Fit::string id {};
    /* * 表示泛服务定义的名字。 */
    Fit::string name {};
    /* * 表示泛服务类型，可选值为 SPI 或 API。 */
    Fit::string type {};
    /* * 表示泛服务的实现列表的相关信息。 */
    Fit::vector<::fit::hakuna::system::worker::FitableInfo> fitableInfos {};
};
}
}
}
}

#endif