/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_QUERYFITABLESADDRESSES_G_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_QUERYFITABLESADDRESSES_G_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_kernel_shared_Fitable/1.0.0/cplusplus/Fitable.hpp>
#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Fitable_instance/1.0.0/cplusplus/FitableInstance.hpp>
#include <fit/stl/vector.hpp>
#include <fit/stl/string.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace server {
struct __queryFitablesAddresses {
    using InType =
        ::Fit::Framework::ArgumentsIn<const Fit::vector<::fit::hakuna::kernel::shared::Fitable> *, const Fit::string *>;
    using OutType =
        ::Fit::Framework::ArgumentsOut<Fit::vector<::fit::hakuna::kernel::registry::shared::FitableInstance> **>;
};

/**
 * @param fitables
 * @param workerId
 * @return
 */
class queryFitablesAddresses : public ::Fit::Framework::ProxyClient<FitCode(__queryFitablesAddresses::InType,
    __queryFitablesAddresses::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "33be4142494e4742aa122555a451d996";
    queryFitablesAddresses()
        : ::Fit::Framework::ProxyClient<FitCode(__queryFitablesAddresses::InType, __queryFitablesAddresses::OutType)>(
        GENERIC_ID)
    {}
    explicit queryFitablesAddresses(ContextObj ctx)
        : ::Fit::Framework::ProxyClient<FitCode(__queryFitablesAddresses::InType, __queryFitablesAddresses::OutType)>(
        GENERIC_ID, ctx)
    {}
    ~queryFitablesAddresses() = default;
};
}
}
}
}
}

#endif
