// automatically generated by the FlatBuffers compiler, do not modify

package modelengine.databus.sdk.message;

@SuppressWarnings("unused")
public final class MessageType {
  private MessageType() { }
  public static final byte Unknown = 0;
  public static final byte Error = 1;
  public static final byte HeartBeat = 16;
  public static final byte RuntimeReport = 17;
  public static final byte ApplyMemory = 32;
  public static final byte ApplyPermission = 33;
  public static final byte ReleasePermission = 48;
  public static final byte ReleaseMemory = 49;
  public static final byte CleanupExpiredMemory = 50;
  public static final byte GetMetaData = 65;
  public static final byte Hello = 66;
}

