// automatically generated by the FlatBuffers compiler, do not modify

package modelengine.databus.sdk.message;

@SuppressWarnings("unused")
public final class PermissionType {
  private PermissionType() { }
  public static final byte None = 0;
  public static final byte Read = 1;
  public static final byte Write = 2;

  public static final String[] names = { "None", "Read", "Write", };

  public static String name(int e) { return names[e]; }
}

