/*---------------------------------------------------------------------------------------------
 *  Copyright (c) 2025 Huawei Technologies Co., Ltd. All rights reserved.
 *  This file is a part of the ModelEngine Project.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// automatically generated by the FlatBuffers compiler, do not modify

package modelengine.databus.sdk.message;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ReleaseMemoryMessage extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_26(); }
  public static ReleaseMemoryMessage getRootAsReleaseMemoryMessage(ByteBuffer _bb) { return getRootAsReleaseMemoryMessage(_bb, new ReleaseMemoryMessage()); }
  public static ReleaseMemoryMessage getRootAsReleaseMemoryMessage(ByteBuffer _bb, ReleaseMemoryMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ReleaseMemoryMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String objectKey() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer objectKeyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer objectKeyInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int memoryKey() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : -1; }

  public static int createReleaseMemoryMessage(FlatBufferBuilder builder,
      int objectKeyOffset,
      int memoryKey) {
    builder.startTable(2);
    ReleaseMemoryMessage.addMemoryKey(builder, memoryKey);
    ReleaseMemoryMessage.addObjectKey(builder, objectKeyOffset);
    return ReleaseMemoryMessage.endReleaseMemoryMessage(builder);
  }

  public static void startReleaseMemoryMessage(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addObjectKey(FlatBufferBuilder builder, int objectKeyOffset) { builder.addOffset(0, objectKeyOffset, 0); }
  public static void addMemoryKey(FlatBufferBuilder builder, int memoryKey) { builder.addInt(1, memoryKey, -1); }
  public static int endReleaseMemoryMessage(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishReleaseMemoryMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedReleaseMemoryMessageBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ReleaseMemoryMessage get(int j) { return get(new ReleaseMemoryMessage(), j); }
    public ReleaseMemoryMessage get(ReleaseMemoryMessage obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

