/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_REGISTERFITABLES_G_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SERVER_REGISTERFITABLES_G_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Application/1.0.0/cplusplus/Application.hpp>
#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Worker/1.0.0/cplusplus/Worker.hpp>
#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Fitable_meta/1.0.0/cplusplus/FitableMeta.hpp>
#include <fit/stl/vector.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace server {
struct __registerFitables {
    using InType =
        ::Fit::Framework::ArgumentsIn<const Fit::vector<::fit::hakuna::kernel::registry::shared::FitableMeta> *,
        const ::fit::hakuna::kernel::registry::shared::Worker *,
        const ::fit::hakuna::kernel::registry::shared::Application *>;
};

/**
 * @param fitableMetas
 * @param worker
 * @param application
 */
class registerFitables : public ::Fit::Framework::ProxyClient<FitCode(__registerFitables::InType)> {
public:
    static constexpr const char *GENERIC_ID = "85bdce64cf724589b87cb6b6a950999d";
    registerFitables() : ::Fit::Framework::ProxyClient<FitCode(__registerFitables::InType)>(GENERIC_ID) {}
    explicit registerFitables(ContextObj ctx)
        : ::Fit::Framework::ProxyClient<FitCode(__registerFitables::InType)>(GENERIC_ID, ctx)
    {}
    ~registerFitables() = default;
};
}
}
}
}
}

#endif
