/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_SERVER_PROCESSV3_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_SERVER_PROCESSV3_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_hakuna_kernel_broker_shared_fit_response/1.0.0/cplusplus/fitResponse.hpp>
#include <fit/stl/string.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace broker {
namespace server {
struct __processV3 {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::bytes *, const Fit::bytes *>;
    using OutType = ::Fit::Framework::ArgumentsOut<::fit::hakuna::kernel::broker::shared::FitResponse **>;
};

/**
 * 引擎内部实现用于接收网络层请求接口
 *
 * @param metadata
 * @param payload
 * @return
 */
class processV3 : public ::Fit::Framework::ProxyClient<FitCode(__processV3::InType, __processV3::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "4c43c13d8a314632844e0a1d9f4b1525";
    processV3() : ::Fit::Framework::ProxyClient<FitCode(__processV3::InType, __processV3::OutType)>(GENERIC_ID) {}
    ~processV3() = default;
};
}
}
}
}
}

#endif
