druid:
  driver-class-name: org.postgresql.Driver
  initialSize: 5
  minIdle: 5
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1
  testWhileIdle: true
  testOnBorrow: true
  testOnReturn: true
  url:
  username:
  password:

corsfilter:
  priority: 50
  patterns: "/**"
  origin: "https://tianzhou.huawei.com"

redis:
  cluster:
    nodes: 7.221.142.173:6379,7.221.143.136:6379,7.221.143.29:6379,7.221.141.9:6379,7.221.141.15:6379,7.221.143.77:6379
    password: enc(2X1X2023080321220040PMdwf7HsYlxgCAlHHJpK6ep1qXgwfFSnP5sx5Ejg0MdAADONsAij9onrEOWVSCJtAwx4hBLVlYsxuIqW2M/CaUmvLWLdkvxjhjtQD8uxq9GdvDwkc2+jpEQ=)

application:
  appId: com.huawei.ipd.tianzhou.framework
  appKey: enc(2X1X2023091410113440De25Aop74H9M/fGFOst+im/3Y8i6upOYKvtoYycKff+QHKUoDij464AKIvedaCwQAww2ZmLvwIDtCMvvpwIfgmMjP6xWgwlc7Ne1txTjuXSyv80AnBU/R7DAiTCLvEbesS6WqMd5)
  appIdStaticToken: enc(2X1X2023080321220040PMdwf7HsYlxgCAlHHJpK6ep1qXgwfFSnP5sx5Ejg0MdAADONsAij9onrEOWVSCJtAwy42wxjGv5uAhC4/G3mQBjOoaNhf9UYTvjXXgHFOGGxepp2YgqMDGDMQT20zWIFlJMIrOSbAyHnb6gEIrQ7dQtcBNCnW5oPGAAM5I/axJtylB5eQLBb53QGsDoH7oQsbQ1Y66uTyhrU9GX9eNoeEd02n5s=)

efs:
  endpoint: http://efs.huawei.com

w3cloud:
  endpoint: http://w3cloud.huawei.com

apig:
  endpoint: http://apigw.huawei.com

jane:
  appId: com.huawei.ipd.jane
  appKey: enc(2X1X20231209092708406pemBd1vqLVKa1sX1onMkzBIpf8qX+V9KSWzVwSLc5CPHoN0iBeo8bExUJ2UIcC8Aww9RdLH+vfpL5ZZHlVY6XdnrpIIiHdKGw9l+IP8WduS4gdR+Uz371bIL1yHvEl9IjBI+wvX)
  appIdStaticToken: enc(2X1X20231209092708406pemBd1vqLVKa1sX1onMkzBIpf8qX+V9KSWzVwSLc5CPHoN0iBeo8bExUJ2UIcC8AwwaSqPlNgvFvvUcdoTHBmJQCuHF0b7pz/TMuxxGB+PTyQ7F/wMAgVQTfOKEKuekRyj3l7F7x1Pwx7ySexZNrtbayD0ffEF8POHaPElaUgsp0tJv7zd9QChq6fR2VsIrEUba2+7r1TZ78a/9Bz0zUoiL6oY=)