druid:
  driver-class-name: org.postgresql.Driver
  initialSize: 5
  minIdle: 5
  maxActive: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 1
  testWhileIdle: true
  testOnBorrow: true
  testOnReturn: true
  url: jdbc:postgresql://7.180.146.52:5432/jane_beta?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useAffectedRows=true
  username: jane
  password: FitLab123

corsfilter:
  priority: 50
  patterns: "/**"
  origin: "https://tianzhou-beta.huawei.com"

redis:
  host: 10.28.40.172
  password: Test@^116Redis
  database: 1

application:
  appId: com.huawei.ipd.tianzhou.framework
  appKey: enc(2X1X202309131126224042S/jeGErynQXD3tHm7gd9b3gKP3zD/cVvrOZS8FzUk+nanKHyQ+i65D/MH5/ouRAwxjwi/JwOylR8t5oe3Ig3+TcxWadijzmcyw45ZZw7+CzEQsnWnCW8InEXwLqlrNhlVKiwh9)
  appIdStaticToken: enc(2X1X2023080820355840Gp4rV2CD+sherQFATTJ7UIny8mBtcCezUImc6BGPhJc2UG2DVbyjS2cVkErO7usBAwzwwCbeXuhIMQUvNK1eSKfnZeuQlAyBLhQiG386xU/ZoqPD7TyeIfGNSJVNp1ztwfawSxeQBhKruj0Kyxy+KxsTbxcOXqC4XdTc7RrWiX3bh5BzQL4+23PYNCQDrXgt1cbufkPFWWK7ZB63dtJO2lRbejA=)

efs:
  endpoint: http://efs-beta.huawei.com

w3cloud:
  endpoint: http://kwe-beta.huawei.com

apig:
  endpoint: http://apigw-beta.huawei.com

jane:
  appId: com.huawei.ipd.jane
  appKey: enc(2X1X2023121316400040ox34qtgXUkHaqidv3OvjQdKtdybCTNktR1uEnqIeDwULJ1A526nIp9pAkpJ7EwsuAww/JX1UHIcfkDTAHHmk6RAAyEtvjGZpHf7mB+Z0hsCjOUVocwDumKai/S8lhYdUwHoelnbg)
  appIdStaticToken: enc(2X1X2023121316400040ox34qtgXUkHaqidv3OvjQdKtdybCTNktR1uEnqIeDwULJ1A526nIp9pAkpJ7EwsuAwy1giLBu4Fgx+Xdv28lvgHMZRrPpeM/vLmEq/qtT8O5959GHHMWN0n817NjaWh/tYxNe7s6rB362D1J30h+gByNrOH2oAvkQgHpS9tSTE29GDnt/jcpynfIXVfgdtlrHa66Pa4EI3YfTtJkitTggqNMqrs=)
