fit:
  beans:
    packages:
      - 'com.huawei.fit.jane'
      - 'com.huawei.fitframework'
      - 'com.huawei.fit.integration'

mybatis:
  mapper-locations: mapper/*Mapper.xml
forest:
  interface-package: com.huawei.fit.jane.external