/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FITLAB_CORE_COMPONENT_ENDPOINT_H
#define COM_HUAWEI_FITLAB_CORE_COMPONENT_ENDPOINT_H

#include <component/com_huawei_fit_hakuna_shared_address/1.0.0/cplusplus/address.hpp>
#include <fit/stl/vector.hpp>
#include <fit/stl/string.hpp>
#include <fit/memory/fit_base.hpp>

namespace fitLab {
namespace core {
namespace component {
struct Endpoint : public FitBase {
    ::fit::hakuna::shared::Address *address;
    /* *
     * rsocket - 0
     * socket - 1
     * http - 2
     * grpc - 3
     * uc - 10
     * shareMemory - 11
     */
    int32_t protocol;
    /* *
     * protobuf - 0
     * json - 1
     */
    Fit::vector<int32_t> serializeFormats;
    Fit::string environment;
    int32_t weight;
};
}
}
}

#endif
