/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_SHARED_FITMETADATA_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_BROKER_SHARED_FITMETADATA_H

#include <fit/stl/string.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace broker {
namespace shared {
struct MetaData : public FitBase {
    uint16_t version;
    uint8_t payloadFormat;
    Fit::string genericableVersion;
    Fit::string genericableId;
    Fit::string fitableId;
    Fit::string accessToken;
    Fit::string tlv;
};
}
}
}
}
}
#endif
