version: 2.0

env:
    resource:
        type: docker
        image: 'kweecr05.his.huawei.com:80/ecr-build-green202/jade_compile_arm_image:jade_test'
        class: 4U4G
        pool: ''
params:
    - name: product
      value: cloudbuild2.0
    - name: CB_AUTO_CHECK_VERSION
      value: 2.0

steps:
    PRE_BUILD:
        - checkout
    BUILD:
        - build_execute:
              command: sh app-builder/frontend/build.sh ${env} ${ssoApi}
              accelerate: false
              check:
                  mode: sync
                  buildcheck: true
                  auto: true
                  dangerouscmd: true
