/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_LOADBALANCE_FILTER_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_LOADBALANCE_FILTER_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fitLab_core_component_Endpoint/1.0.0/cplusplus/Endpoint.hpp>
#include <fit/stl/vector.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace loadbalance {
struct __filter {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::vector<::fitLab::core::component::Endpoint> *>;
    using OutType = ::Fit::Framework::ArgumentsOut<Fit::vector<::fitLab::core::component::Endpoint> **>;
};

/**
 * 过滤从注册中心获取到的目标地址列表。
 *
 * @param endpoints 表示待过滤的目标地址列表。
 * @return 表示过滤后的目标地址列表。
 */
class filter : public ::Fit::Framework::ProxyClient<FitCode(__filter::InType, __filter::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "d58a444c9cd546b5b284353c0326209c";
    filter() : ::Fit::Framework::ProxyClient<FitCode(__filter::InType, __filter::OutType)>(GENERIC_ID) {}
    ~filter() = default;
};
}
}
}
}

#endif
