/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HEARTBEAT_SUBSCRIBEHEARTBEAT_H
#define COM_HUAWEI_FIT_HEARTBEAT_SUBSCRIBEHEARTBEAT_H

#include <fit/external/framework/proxy_client.hpp>

#include <component/com_huawei_fit_registry_registry_common/1.0.0/cplusplus/registryCommon.hpp>
#include <component/com_huawei_fit_heartbeat_heartbeat_common/1.0.0/cplusplus/heartbeatCommon.hpp>
#include <fit/stl/vector.hpp>

namespace fit {
namespace heartbeat {
struct __subscribeHeartbeat {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::vector<::fit::heartbeat::SubscribeBeatInfo> *,
        const ::fit::registry::Address *>;
    using OutType = ::Fit::Framework::ArgumentsOut<bool **>;
};

class subscribeHeartbeat
    : public ::Fit::Framework::ProxyClient<FitCode(__subscribeHeartbeat::InType, __subscribeHeartbeat::OutType)> {
public:
    static constexpr const char *GENERIC_ID = "e9226b30e8f54d53aea42f422dcbb54b";
    subscribeHeartbeat()
        : ::Fit::Framework::ProxyClient<FitCode(__subscribeHeartbeat::InType, __subscribeHeartbeat::OutType)>(
        GENERIC_ID)
    {}
    ~subscribeHeartbeat() = default;
};
}
}

#endif