/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_MATATA_CONF_CLIENT_UPLOAD_H
#define COM_HUAWEI_MATATA_CONF_CLIENT_UPLOAD_H

#include <fit/external/framework/proxy_client.hpp>

#include <fit/stl/string.hpp>
#include <fit/stl/map.hpp>

namespace matata {
namespace conf {
namespace client {
struct __upload {
    using InType = ::Fit::Framework::ArgumentsIn<const Fit::string *, const Fit::map<Fit::string, Fit::string> *>;
};

/**
 * 上传配置。
 *
 * @param key 表示配置的键。将以“.”分割成路径。
 * @param values 表示配置的值。
 */
class upload : public ::Fit::Framework::ProxyClient<FitCode(__upload::InType)> {
public:
    static constexpr const char *GENERIC_ID = "90c52daf8cc14e22ad8cfb9a19d21157";
    upload() : ::Fit::Framework::ProxyClient<FitCode(__upload::InType)>(GENERIC_ID) {}
    ~upload() = default;
};
}
}
}

#endif
