/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_ADDRESS_C_H
#define COM_HUAWEI_FIT_HAKUNA_KERNEL_REGISTRY_SHARED_ADDRESS_C_H

#include <component/com_huawei_fit_hakuna_kernel_registry_shared_Endpoint/1.0.0/cplusplus/Endpoint.hpp>
#include <fit/stl/string.hpp>
#include <fit/stl/vector.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace kernel {
namespace registry {
namespace shared {
struct Address : public FitBase {
    Fit::string host {};
    Fit::vector<::fit::hakuna::kernel::registry::shared::Endpoint> endpoints {};
};
}
}
}
}
}

#endif