---
version: 2.0

env:
  resource:
    type: docker
    image: 'kweecr04.his.huawei.com:80/ecr-build-arm-gzkunpeng/docker_eulerv200r012b150_x86_gy202y_builduser:202403111835'
    class: 4U4G
    pool: ''
params:
  - name: product
    value: cloudbud2.0
  - name: CB_AUTO_CHECK_VERSION
    value: 2.0

steps:
  PRE_BUILD:
    - checkout

  BUILD:
    - build_execute:
        command: sh ./.cloudbuild/framework/elsa/react/build.sh
        enhance:
          - feature: md5_source_tracement
            build_tools: [npm]
        check:
          mode: sync
          auto: true