/*
* Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
* Description:
* Author: auto generated by FIT IDL
* Date:
*/

#include <fit/external/framework/annotation/fitable_registrar.hpp>
#include <genericable/com_huawei_fit_hakuna_kernel_registry_server_remove_resgitry_address/1.0.0/cplusplus/removeResgitryAddress.hpp>
#include <fit/fit_log.h>
namespace {
FitCode RemoveResgitryAddress(ContextObj ctx,
    const ::fit::registry::Address *address,
    int32_t **result)
{
    if (address == nullptr) {
        FIT_LOG_ERROR("Remove registry address param is nullptr.");
        return FIT_ERR_FAIL;
    }
    *result = Fit::Context::NewObj<int32_t>(ctx);
    **result = FIT_OK;
    FIT_LOG_CORE("Remove registry address, worker id is %s.", address->id.c_str());
    return FIT_ERR_SUCCESS;
}
}

FIT_REGISTRATIONS
{
    ::Fit::Framework::Annotation::Fitable(::RemoveResgitryAddress)
        .SetGenericId(fit::hakuna::kernel::registry::server::removeResgitryAddress::GENERIC_ID)
        .SetFitableId("6cf7ee3ff164422c97bc7b128f2f02e8");
}