/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 * Description:
 * Author: auto generated by FIT IDL
 * Date:
 */

#ifndef COM_HUAWEI_FIT_HAKUNA_SYSTEM_WORKER_FITABLEINFO_H
#define COM_HUAWEI_FIT_HAKUNA_SYSTEM_WORKER_FITABLEINFO_H

#include <fit/stl/string.hpp>
#include <fit/stl/vector.hpp>
#include <fit/memory/fit_base.hpp>

namespace fit {
namespace hakuna {
namespace system {
namespace worker {
/* * 泛服务实现的相关信息。 */
struct FitableInfo : public FitBase {
    /* * 表示泛服务实现的唯一标识。 */
    Fit::string id {};
    /* * 表示泛服务实现的别名列表。 */
    Fit::vector<Fit::string> aliases {};
    /* * 表示泛服务实现的运行状态。 */
    Fit::string status {};
};
}
}
}
}

#endif