/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter */

#ifndef _Included_com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter
#define _Included_com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter
 * Method:    read
 * Signature: (IJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter_read
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter
 * Method:    write
 * Signature: (IJJ[B)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter_write
  (JNIEnv *, jobject, jint, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
