/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.
 */

#ifndef COM_HUAWEI_DATABUS_SDK_CLIENT_JNI_SHAREDMEMORYREADERWRITER_H
#define COM_HUAWEI_DATABUS_SDK_CLIENT_JNI_SHAREDMEMORYREADERWRITER_H

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter */

#ifndef _Included_com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter
 * Method:    read
 * Signature: (IJJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter_read
  (JNIEnv *, jobject, jint, jlong, jlong);

/*
 * Class:     com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter
 * Method:    write
 * Signature: (IJJ[B)J
 */
JNIEXPORT jlong JNICALL Java_com_huawei_databus_sdk_client_jni_SharedMemoryReaderWriter_write
  (JNIEnv *, jobject, jint, jlong, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
#endif

